// Copyright 2026 The Agent Substrate Authors.
//
// Minimal Protocol Buffers definition for the Agent Substrate Guest Data Plane.
// Exposes asynchronous process execution, log streaming, and streaming file I/O.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.0
// source: ateenv/v1/guest.proto

package ateenvv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProcessService_StartProcess_FullMethodName      = "/ateenv.v1.ProcessService/StartProcess"
	ProcessService_GetProcess_FullMethodName        = "/ateenv.v1.ProcessService/GetProcess"
	ProcessService_StreamProcessLogs_FullMethodName = "/ateenv.v1.ProcessService/StreamProcessLogs"
	ProcessService_WriteStdin_FullMethodName        = "/ateenv.v1.ProcessService/WriteStdin"
	ProcessService_KillProcess_FullMethodName       = "/ateenv.v1.ProcessService/KillProcess"
)

// ProcessServiceClient is the client API for ProcessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProcessService manages the asynchronous lifecycle and output streaming of
// processes running inside the container.
//
// The service is built for disposable connections: every call is short-lived
// (StreamProcessLogs is bounded unless follow is set), and the durable
// handles are process ids and byte offsets, never a connection. A client
// that loses its connection — or whose environment is suspended and later
// resumed — polls again with the same handles and continues where it left
// off.
type ProcessServiceClient interface {
	// StartProcess launches a long-running process asynchronously in the background
	// and immediately returns a unique process_id for tracking.
	StartProcess(ctx context.Context, in *StartProcessRequest, opts ...grpc.CallOption) (*StartProcessResponse, error)
	// GetProcess retrieves the current metadata, lifecycle state, and timestamps of a process.
	GetProcess(ctx context.Context, in *GetProcessRequest, opts ...grpc.CallOption) (*Process, error)
	// StreamProcessLogs streams stdout and stderr logs from a process: with
	// follow, in real time until the process exits; without it, a bounded
	// snapshot of what the requested offsets have not seen yet, optionally
	// long-polling up to wait_ms. Poll again from the previous offsets plus
	// the bytes received to consume output incrementally.
	StreamProcessLogs(ctx context.Context, in *StreamProcessLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProcessLogChunk], error)
	// WriteStdin forwards data to the standard input of a process started
	// with stdin, and optionally closes it, delivering EOF.
	WriteStdin(ctx context.Context, in *WriteStdinRequest, opts ...grpc.CallOption) (*WriteStdinResponse, error)
	// KillProcess signals a running asynchronous process and its child process
	// tree (SIGKILL unless the request names another signal).
	KillProcess(ctx context.Context, in *KillProcessRequest, opts ...grpc.CallOption) (*KillProcessResponse, error)
}

type processServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessServiceClient(cc grpc.ClientConnInterface) ProcessServiceClient {
	return &processServiceClient{cc}
}

func (c *processServiceClient) StartProcess(ctx context.Context, in *StartProcessRequest, opts ...grpc.CallOption) (*StartProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartProcessResponse)
	err := c.cc.Invoke(ctx, ProcessService_StartProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processServiceClient) GetProcess(ctx context.Context, in *GetProcessRequest, opts ...grpc.CallOption) (*Process, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Process)
	err := c.cc.Invoke(ctx, ProcessService_GetProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processServiceClient) StreamProcessLogs(ctx context.Context, in *StreamProcessLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProcessLogChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProcessService_ServiceDesc.Streams[0], ProcessService_StreamProcessLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamProcessLogsRequest, ProcessLogChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessService_StreamProcessLogsClient = grpc.ServerStreamingClient[ProcessLogChunk]

func (c *processServiceClient) WriteStdin(ctx context.Context, in *WriteStdinRequest, opts ...grpc.CallOption) (*WriteStdinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteStdinResponse)
	err := c.cc.Invoke(ctx, ProcessService_WriteStdin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processServiceClient) KillProcess(ctx context.Context, in *KillProcessRequest, opts ...grpc.CallOption) (*KillProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KillProcessResponse)
	err := c.cc.Invoke(ctx, ProcessService_KillProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProcessServiceServer is the server API for ProcessService service.
// All implementations must embed UnimplementedProcessServiceServer
// for forward compatibility.
//
// ProcessService manages the asynchronous lifecycle and output streaming of
// processes running inside the container.
//
// The service is built for disposable connections: every call is short-lived
// (StreamProcessLogs is bounded unless follow is set), and the durable
// handles are process ids and byte offsets, never a connection. A client
// that loses its connection — or whose environment is suspended and later
// resumed — polls again with the same handles and continues where it left
// off.
type ProcessServiceServer interface {
	// StartProcess launches a long-running process asynchronously in the background
	// and immediately returns a unique process_id for tracking.
	StartProcess(context.Context, *StartProcessRequest) (*StartProcessResponse, error)
	// GetProcess retrieves the current metadata, lifecycle state, and timestamps of a process.
	GetProcess(context.Context, *GetProcessRequest) (*Process, error)
	// StreamProcessLogs streams stdout and stderr logs from a process: with
	// follow, in real time until the process exits; without it, a bounded
	// snapshot of what the requested offsets have not seen yet, optionally
	// long-polling up to wait_ms. Poll again from the previous offsets plus
	// the bytes received to consume output incrementally.
	StreamProcessLogs(*StreamProcessLogsRequest, grpc.ServerStreamingServer[ProcessLogChunk]) error
	// WriteStdin forwards data to the standard input of a process started
	// with stdin, and optionally closes it, delivering EOF.
	WriteStdin(context.Context, *WriteStdinRequest) (*WriteStdinResponse, error)
	// KillProcess signals a running asynchronous process and its child process
	// tree (SIGKILL unless the request names another signal).
	KillProcess(context.Context, *KillProcessRequest) (*KillProcessResponse, error)
	mustEmbedUnimplementedProcessServiceServer()
}

// UnimplementedProcessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProcessServiceServer struct{}

func (UnimplementedProcessServiceServer) StartProcess(context.Context, *StartProcessRequest) (*StartProcessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartProcess not implemented")
}
func (UnimplementedProcessServiceServer) GetProcess(context.Context, *GetProcessRequest) (*Process, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProcess not implemented")
}
func (UnimplementedProcessServiceServer) StreamProcessLogs(*StreamProcessLogsRequest, grpc.ServerStreamingServer[ProcessLogChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamProcessLogs not implemented")
}
func (UnimplementedProcessServiceServer) WriteStdin(context.Context, *WriteStdinRequest) (*WriteStdinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteStdin not implemented")
}
func (UnimplementedProcessServiceServer) KillProcess(context.Context, *KillProcessRequest) (*KillProcessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KillProcess not implemented")
}
func (UnimplementedProcessServiceServer) mustEmbedUnimplementedProcessServiceServer() {}
func (UnimplementedProcessServiceServer) testEmbeddedByValue()                        {}

// UnsafeProcessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcessServiceServer will
// result in compilation errors.
type UnsafeProcessServiceServer interface {
	mustEmbedUnimplementedProcessServiceServer()
}

func RegisterProcessServiceServer(s grpc.ServiceRegistrar, srv ProcessServiceServer) {
	// If the following call panics, it indicates UnimplementedProcessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProcessService_ServiceDesc, srv)
}

func _ProcessService_StartProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessServiceServer).StartProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessService_StartProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessServiceServer).StartProcess(ctx, req.(*StartProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessService_GetProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessServiceServer).GetProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessService_GetProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessServiceServer).GetProcess(ctx, req.(*GetProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessService_StreamProcessLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamProcessLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProcessServiceServer).StreamProcessLogs(m, &grpc.GenericServerStream[StreamProcessLogsRequest, ProcessLogChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessService_StreamProcessLogsServer = grpc.ServerStreamingServer[ProcessLogChunk]

func _ProcessService_WriteStdin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteStdinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessServiceServer).WriteStdin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessService_WriteStdin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessServiceServer).WriteStdin(ctx, req.(*WriteStdinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessService_KillProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessServiceServer).KillProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessService_KillProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessServiceServer).KillProcess(ctx, req.(*KillProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProcessService_ServiceDesc is the grpc.ServiceDesc for ProcessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProcessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ateenv.v1.ProcessService",
	HandlerType: (*ProcessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartProcess",
			Handler:    _ProcessService_StartProcess_Handler,
		},
		{
			MethodName: "GetProcess",
			Handler:    _ProcessService_GetProcess_Handler,
		},
		{
			MethodName: "WriteStdin",
			Handler:    _ProcessService_WriteStdin_Handler,
		},
		{
			MethodName: "KillProcess",
			Handler:    _ProcessService_KillProcess_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamProcessLogs",
			Handler:       _ProcessService_StreamProcessLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ateenv/v1/guest.proto",
}

const (
	FileSystemService_ReadFile_FullMethodName   = "/ateenv.v1.FileSystemService/ReadFile"
	FileSystemService_WriteFile_FullMethodName  = "/ateenv.v1.FileSystemService/WriteFile"
	FileSystemService_StatFile_FullMethodName   = "/ateenv.v1.FileSystemService/StatFile"
	FileSystemService_ListDir_FullMethodName    = "/ateenv.v1.FileSystemService/ListDir"
	FileSystemService_MakeDir_FullMethodName    = "/ateenv.v1.FileSystemService/MakeDir"
	FileSystemService_RemovePath_FullMethodName = "/ateenv.v1.FileSystemService/RemovePath"
)

// FileSystemServiceClient is the client API for FileSystemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FileSystemService provides streaming file reading and writing capabilities inside
// the container rootfs/workspace to prevent memory exhaustion (OOM), plus
// plain metadata operations whose failures map onto gRPC status codes
// (NOT_FOUND, INVALID_ARGUMENT, ...).
type FileSystemServiceClient interface {
	// ReadFile streams the binary or text contents of a file in chunks.
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error)
	// WriteFile streams binary or text chunks directly to a target file. The
	// file is written to a temporary path and atomically renamed into place on
	// success, so a failed or abandoned upload never leaves a partial file.
	WriteFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteFileRequest, WriteFileResponse], error)
	// StatFile returns metadata for a file or directory.
	StatFile(ctx context.Context, in *StatFileRequest, opts ...grpc.CallOption) (*FileInfo, error)
	// ListDir returns the immediate entries of a directory.
	ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error)
	// MakeDir creates a directory.
	MakeDir(ctx context.Context, in *MakeDirRequest, opts ...grpc.CallOption) (*MakeDirResponse, error)
	// RemovePath deletes a file or directory.
	RemovePath(ctx context.Context, in *RemovePathRequest, opts ...grpc.CallOption) (*RemovePathResponse, error)
}

type fileSystemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileSystemServiceClient(cc grpc.ClientConnInterface) FileSystemServiceClient {
	return &fileSystemServiceClient{cc}
}

func (c *fileSystemServiceClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileSystemService_ServiceDesc.Streams[0], FileSystemService_ReadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadFileRequest, FileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileSystemService_ReadFileClient = grpc.ServerStreamingClient[FileChunk]

func (c *fileSystemServiceClient) WriteFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteFileRequest, WriteFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileSystemService_ServiceDesc.Streams[1], FileSystemService_WriteFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WriteFileRequest, WriteFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileSystemService_WriteFileClient = grpc.ClientStreamingClient[WriteFileRequest, WriteFileResponse]

func (c *fileSystemServiceClient) StatFile(ctx context.Context, in *StatFileRequest, opts ...grpc.CallOption) (*FileInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileInfo)
	err := c.cc.Invoke(ctx, FileSystemService_StatFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileSystemServiceClient) ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDirResponse)
	err := c.cc.Invoke(ctx, FileSystemService_ListDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileSystemServiceClient) MakeDir(ctx context.Context, in *MakeDirRequest, opts ...grpc.CallOption) (*MakeDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MakeDirResponse)
	err := c.cc.Invoke(ctx, FileSystemService_MakeDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileSystemServiceClient) RemovePath(ctx context.Context, in *RemovePathRequest, opts ...grpc.CallOption) (*RemovePathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemovePathResponse)
	err := c.cc.Invoke(ctx, FileSystemService_RemovePath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileSystemServiceServer is the server API for FileSystemService service.
// All implementations must embed UnimplementedFileSystemServiceServer
// for forward compatibility.
//
// FileSystemService provides streaming file reading and writing capabilities inside
// the container rootfs/workspace to prevent memory exhaustion (OOM), plus
// plain metadata operations whose failures map onto gRPC status codes
// (NOT_FOUND, INVALID_ARGUMENT, ...).
type FileSystemServiceServer interface {
	// ReadFile streams the binary or text contents of a file in chunks.
	ReadFile(*ReadFileRequest, grpc.ServerStreamingServer[FileChunk]) error
	// WriteFile streams binary or text chunks directly to a target file. The
	// file is written to a temporary path and atomically renamed into place on
	// success, so a failed or abandoned upload never leaves a partial file.
	WriteFile(grpc.ClientStreamingServer[WriteFileRequest, WriteFileResponse]) error
	// StatFile returns metadata for a file or directory.
	StatFile(context.Context, *StatFileRequest) (*FileInfo, error)
	// ListDir returns the immediate entries of a directory.
	ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error)
	// MakeDir creates a directory.
	MakeDir(context.Context, *MakeDirRequest) (*MakeDirResponse, error)
	// RemovePath deletes a file or directory.
	RemovePath(context.Context, *RemovePathRequest) (*RemovePathResponse, error)
	mustEmbedUnimplementedFileSystemServiceServer()
}

// UnimplementedFileSystemServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileSystemServiceServer struct{}

func (UnimplementedFileSystemServiceServer) ReadFile(*ReadFileRequest, grpc.ServerStreamingServer[FileChunk]) error {
	return status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedFileSystemServiceServer) WriteFile(grpc.ClientStreamingServer[WriteFileRequest, WriteFileResponse]) error {
	return status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedFileSystemServiceServer) StatFile(context.Context, *StatFileRequest) (*FileInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method StatFile not implemented")
}
func (UnimplementedFileSystemServiceServer) ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDir not implemented")
}
func (UnimplementedFileSystemServiceServer) MakeDir(context.Context, *MakeDirRequest) (*MakeDirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MakeDir not implemented")
}
func (UnimplementedFileSystemServiceServer) RemovePath(context.Context, *RemovePathRequest) (*RemovePathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemovePath not implemented")
}
func (UnimplementedFileSystemServiceServer) mustEmbedUnimplementedFileSystemServiceServer() {}
func (UnimplementedFileSystemServiceServer) testEmbeddedByValue()                           {}

// UnsafeFileSystemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileSystemServiceServer will
// result in compilation errors.
type UnsafeFileSystemServiceServer interface {
	mustEmbedUnimplementedFileSystemServiceServer()
}

func RegisterFileSystemServiceServer(s grpc.ServiceRegistrar, srv FileSystemServiceServer) {
	// If the following call panics, it indicates UnimplementedFileSystemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileSystemService_ServiceDesc, srv)
}

func _FileSystemService_ReadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileSystemServiceServer).ReadFile(m, &grpc.GenericServerStream[ReadFileRequest, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileSystemService_ReadFileServer = grpc.ServerStreamingServer[FileChunk]

func _FileSystemService_WriteFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileSystemServiceServer).WriteFile(&grpc.GenericServerStream[WriteFileRequest, WriteFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileSystemService_WriteFileServer = grpc.ClientStreamingServer[WriteFileRequest, WriteFileResponse]

func _FileSystemService_StatFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileSystemServiceServer).StatFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileSystemService_StatFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileSystemServiceServer).StatFile(ctx, req.(*StatFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileSystemService_ListDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileSystemServiceServer).ListDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileSystemService_ListDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileSystemServiceServer).ListDir(ctx, req.(*ListDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileSystemService_MakeDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileSystemServiceServer).MakeDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileSystemService_MakeDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileSystemServiceServer).MakeDir(ctx, req.(*MakeDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileSystemService_RemovePath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileSystemServiceServer).RemovePath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileSystemService_RemovePath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileSystemServiceServer).RemovePath(ctx, req.(*RemovePathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileSystemService_ServiceDesc is the grpc.ServiceDesc for FileSystemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileSystemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ateenv.v1.FileSystemService",
	HandlerType: (*FileSystemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StatFile",
			Handler:    _FileSystemService_StatFile_Handler,
		},
		{
			MethodName: "ListDir",
			Handler:    _FileSystemService_ListDir_Handler,
		},
		{
			MethodName: "MakeDir",
			Handler:    _FileSystemService_MakeDir_Handler,
		},
		{
			MethodName: "RemovePath",
			Handler:    _FileSystemService_RemovePath_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadFile",
			Handler:       _FileSystemService_ReadFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WriteFile",
			Handler:       _FileSystemService_WriteFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "ateenv/v1/guest.proto",
}
