// Copyright 2026 The Agent Substrate Authors.
//
// Minimal Protocol Buffers definition for the Agent Substrate Guest Data Plane.
// Exposes asynchronous process execution, log streaming, and streaming file I/O.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: proto/ateenv/v1/guest.proto

package ateenvv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Execution status of an asynchronous process.
type ProcessStatus int32

const (
	ProcessStatus_PROCESS_STATUS_UNSPECIFIED ProcessStatus = 0
	// Process is actively running in the background.
	ProcessStatus_PROCESS_STATUS_RUNNING ProcessStatus = 1
	// Process completed successfully with exit code 0.
	ProcessStatus_PROCESS_STATUS_COMPLETED ProcessStatus = 2
	// Process completed with a non-zero exit code or failed to run.
	ProcessStatus_PROCESS_STATUS_FAILED ProcessStatus = 3
	// Process was killed before completion.
	ProcessStatus_PROCESS_STATUS_TERMINATED ProcessStatus = 4
)

// Enum value maps for ProcessStatus.
var (
	ProcessStatus_name = map[int32]string{
		0: "PROCESS_STATUS_UNSPECIFIED",
		1: "PROCESS_STATUS_RUNNING",
		2: "PROCESS_STATUS_COMPLETED",
		3: "PROCESS_STATUS_FAILED",
		4: "PROCESS_STATUS_TERMINATED",
	}
	ProcessStatus_value = map[string]int32{
		"PROCESS_STATUS_UNSPECIFIED": 0,
		"PROCESS_STATUS_RUNNING":     1,
		"PROCESS_STATUS_COMPLETED":   2,
		"PROCESS_STATUS_FAILED":      3,
		"PROCESS_STATUS_TERMINATED":  4,
	}
)

func (x ProcessStatus) Enum() *ProcessStatus {
	p := new(ProcessStatus)
	*p = x
	return p
}

func (x ProcessStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ateenv_v1_guest_proto_enumTypes[0].Descriptor()
}

func (ProcessStatus) Type() protoreflect.EnumType {
	return &file_proto_ateenv_v1_guest_proto_enumTypes[0]
}

func (x ProcessStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessStatus.Descriptor instead.
func (ProcessStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_ateenv_v1_guest_proto_rawDescGZIP(), []int{0}
}

// Output log stream source.
type LogSource int32

const (
	LogSource_LOG_SOURCE_UNSPECIFIED LogSource = 0
	LogSource_LOG_SOURCE_STDOUT      LogSource = 1
	LogSource_LOG_SOURCE_STDERR      LogSource = 2
)

// Enum value maps for LogSource.
var (
	LogSource_name = map[int32]string{
		0: "LOG_SOURCE_UNSPECIFIED",
		1: "LOG_SOURCE_STDOUT",
		2: "LOG_SOURCE_STDERR",
	}
	LogSource_value = map[string]int32{
		"LOG_SOURCE_UNSPECIFIED": 0,
		"LOG_SOURCE_STDOUT":      1,
		"LOG_SOURCE_STDERR":      2,
	}
)

func (x LogSource) Enum() *LogSource {
	p := new(LogSource)
	*p = x
	return p
}

func (x LogSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogSource) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ateenv_v1_guest_proto_enumTypes[1].Descriptor()
}

func (LogSource) Type() protoreflect.EnumType {
	return &file_proto_ateenv_v1_guest_proto_enumTypes[1]
}

func (x LogSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogSource.Descriptor instead.
func (LogSource) EnumDescriptor() ([]byte, []int) {
	return file_proto_ateenv_v1_guest_proto_rawDescGZIP(), []int{1}
}

// The Process resource representing execution state and metadata.
type Process struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique process identifier.
	ProcessId string `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	// Current execution lifecycle state.
	Status ProcessStatus `protobuf:"varint,2,opt,name=status,proto3,enum=ateenv.v1.ProcessStatus" json:"status,omitempty"`
	// Process exit status code (0 for success, 1-127 for program exit code,
	// 128 + signal number if terminated by signal, e.g. 137 for SIGKILL, 143 for SIGTERM).
	// Valid once status is COMPLETED, FAILED, or TERMINATED.
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Timestamp when the process started.
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// Timestamp when the process terminated (if finished).
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Process) Reset() {
	*x = Process{}
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1_guest_proto_rawDescGZIP(), []int{0}
}

func (x *Process) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *Process) GetStatus() ProcessStatus {
	if x != nil {
		return x.Status
	}
	return ProcessStatus_PROCESS_STATUS_UNSPECIFIED
}

func (x *Process) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *Process) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Process) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

// Request to start a background asynchronous process.
type StartProcessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command binary and arguments to execute (e.g. ["pytest", "tests/"] or ["sh", "-c", "ls -la"]).
	Command []string `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	// Working directory inside the container (defaults to container workdir).
	Cwd string `protobuf:"bytes,2,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// Environment variables to set for the background process.
	Env           map[string]string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProcessRequest) Reset() {
	*x = StartProcessRequest{}
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessRequest) ProtoMessage() {}

func (x *StartProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessRequest.ProtoReflect.Descriptor instead.
func (*StartProcessRequest) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1_guest_proto_rawDescGZIP(), []int{1}
}

func (x *StartProcessRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *StartProcessRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *StartProcessRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

// Response returned immediately after launching an asynchronous process.
type StartProcessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique process identifier used for status inspection, log streaming, and killing.
	ProcessId     string `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProcessResponse) Reset() {
	*x = StartProcessResponse{}
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessResponse) ProtoMessage() {}

func (x *StartProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessResponse.ProtoReflect.Descriptor instead.
func (*StartProcessResponse) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1_guest_proto_rawDescGZIP(), []int{2}
}

func (x *StartProcessResponse) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

// Request to get the Process resource.
type GetProcessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the process to inspect.
	ProcessId     string `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessRequest) Reset() {
	*x = GetProcessRequest{}
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessRequest) ProtoMessage() {}

func (x *GetProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessRequest.ProtoReflect.Descriptor instead.
func (*GetProcessRequest) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1_guest_proto_rawDescGZIP(), []int{3}
}

func (x *GetProcessRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

// Request to stream logs from a process.
type StreamProcessLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the process to stream logs from.
	ProcessId string `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	// Byte offset to start reading stdout from (defaults to 0 / beginning).
	StdoutOffset int64 `protobuf:"varint,2,opt,name=stdout_offset,json=stdoutOffset,proto3" json:"stdout_offset,omitempty"`
	// Byte offset to start reading stderr from (defaults to 0 / beginning).
	StderrOffset int64 `protobuf:"varint,3,opt,name=stderr_offset,json=stderrOffset,proto3" json:"stderr_offset,omitempty"`
	// If true, the stream follows new log output in real-time until the process finishes.
	Follow        bool `protobuf:"varint,4,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamProcessLogsRequest) Reset() {
	*x = StreamProcessLogsRequest{}
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamProcessLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamProcessLogsRequest) ProtoMessage() {}

func (x *StreamProcessLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamProcessLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamProcessLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1_guest_proto_rawDescGZIP(), []int{4}
}

func (x *StreamProcessLogsRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *StreamProcessLogsRequest) GetStdoutOffset() int64 {
	if x != nil {
		return x.StdoutOffset
	}
	return 0
}

func (x *StreamProcessLogsRequest) GetStderrOffset() int64 {
	if x != nil {
		return x.StderrOffset
	}
	return 0
}

func (x *StreamProcessLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

// Streamed chunk of process output.
type ProcessLogChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stream source (stdout or stderr).
	Source LogSource `protobuf:"varint,1,opt,name=source,proto3,enum=ateenv.v1.LogSource" json:"source,omitempty"`
	// Log content bytes.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessLogChunk) Reset() {
	*x = ProcessLogChunk{}
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessLogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessLogChunk) ProtoMessage() {}

func (x *ProcessLogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessLogChunk.ProtoReflect.Descriptor instead.
func (*ProcessLogChunk) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1_guest_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessLogChunk) GetSource() LogSource {
	if x != nil {
		return x.Source
	}
	return LogSource_LOG_SOURCE_UNSPECIFIED
}

func (x *ProcessLogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Request to terminate a running asynchronous process.
type KillProcessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the background process to terminate.
	ProcessId     string `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillProcessRequest) Reset() {
	*x = KillProcessRequest{}
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillProcessRequest) ProtoMessage() {}

func (x *KillProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillProcessRequest.ProtoReflect.Descriptor instead.
func (*KillProcessRequest) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1_guest_proto_rawDescGZIP(), []int{6}
}

func (x *KillProcessRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

// Response from terminating a process.
type KillProcessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exit status code after process termination (typically 128 + signal, e.g. 137 for SIGKILL).
	ExitCode      int32 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillProcessResponse) Reset() {
	*x = KillProcessResponse{}
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillProcessResponse) ProtoMessage() {}

func (x *KillProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillProcessResponse.ProtoReflect.Descriptor instead.
func (*KillProcessResponse) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1_guest_proto_rawDescGZIP(), []int{7}
}

func (x *KillProcessResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

// Request to read a file from the container.
type ReadFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute or workspace-relative path of the file to read.
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1_guest_proto_rawDescGZIP(), []int{8}
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Streamed chunk of file data.
type FileChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw binary or text chunk of the file.
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1_guest_proto_rawDescGZIP(), []int{9}
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Streamed request chunk for writing data to a file.
type WriteFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute or workspace-relative path of the file to write (sent on first message).
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Raw binary or text chunk to write to the file.
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	// Optional POSIX file mode permission (e.g. 0644 or 0755; processed on first message).
	Mode          uint32 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1_guest_proto_rawDescGZIP(), []int{10}
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *WriteFileRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// Response confirming the write operation.
type WriteFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of bytes written across all stream chunks.
	BytesWritten  int64 `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1_guest_proto_rawDescGZIP(), []int{11}
}

func (x *WriteFileResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

var File_proto_ateenv_v1_guest_proto protoreflect.FileDescriptor

const file_proto_ateenv_v1_guest_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/ateenv/v1/guest.proto\x12\tateenv.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xef\x01\n" +
	"\aProcess\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.ateenv.v1.ProcessStatusR\x06status\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\"\xb4\x01\n" +
	"\x13StartProcessRequest\x12\x18\n" +
	"\acommand\x18\x01 \x03(\tR\acommand\x12\x10\n" +
	"\x03cwd\x18\x02 \x01(\tR\x03cwd\x129\n" +
	"\x03env\x18\x03 \x03(\v2'.ateenv.v1.StartProcessRequest.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"5\n" +
	"\x14StartProcessResponse\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\"2\n" +
	"\x11GetProcessRequest\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\"\x9b\x01\n" +
	"\x18StreamProcessLogsRequest\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12#\n" +
	"\rstdout_offset\x18\x02 \x01(\x03R\fstdoutOffset\x12#\n" +
	"\rstderr_offset\x18\x03 \x01(\x03R\fstderrOffset\x12\x16\n" +
	"\x06follow\x18\x04 \x01(\bR\x06follow\"S\n" +
	"\x0fProcessLogChunk\x12,\n" +
	"\x06source\x18\x01 \x01(\x0e2\x14.ateenv.v1.LogSourceR\x06source\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"3\n" +
	"\x12KillProcessRequest\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\"2\n" +
	"\x13KillProcessResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\"%\n" +
	"\x0fReadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x1f\n" +
	"\tFileChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"P\n" +
	"\x10WriteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\fR\x05chunk\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\"8\n" +
	"\x11WriteFileResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x03R\fbytesWritten*\xa3\x01\n" +
	"\rProcessStatus\x12\x1e\n" +
	"\x1aPROCESS_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PROCESS_STATUS_RUNNING\x10\x01\x12\x1c\n" +
	"\x18PROCESS_STATUS_COMPLETED\x10\x02\x12\x19\n" +
	"\x15PROCESS_STATUS_FAILED\x10\x03\x12\x1d\n" +
	"\x19PROCESS_STATUS_TERMINATED\x10\x04*U\n" +
	"\tLogSource\x12\x1a\n" +
	"\x16LOG_SOURCE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11LOG_SOURCE_STDOUT\x10\x01\x12\x15\n" +
	"\x11LOG_SOURCE_STDERR\x10\x022\xc7\x02\n" +
	"\x0eProcessService\x12O\n" +
	"\fStartProcess\x12\x1e.ateenv.v1.StartProcessRequest\x1a\x1f.ateenv.v1.StartProcessResponse\x12>\n" +
	"\n" +
	"GetProcess\x12\x1c.ateenv.v1.GetProcessRequest\x1a\x12.ateenv.v1.Process\x12V\n" +
	"\x11StreamProcessLogs\x12#.ateenv.v1.StreamProcessLogsRequest\x1a\x1a.ateenv.v1.ProcessLogChunk0\x01\x12L\n" +
	"\vKillProcess\x12\x1d.ateenv.v1.KillProcessRequest\x1a\x1e.ateenv.v1.KillProcessResponse2\x9d\x01\n" +
	"\x11FileSystemService\x12>\n" +
	"\bReadFile\x12\x1a.ateenv.v1.ReadFileRequest\x1a\x14.ateenv.v1.FileChunk0\x01\x12H\n" +
	"\tWriteFile\x12\x1b.ateenv.v1.WriteFileRequest\x1a\x1c.ateenv.v1.WriteFileResponse(\x01B9Z7github.com/agent-substrate/env/proto/ateenv/v1;ateenvv1b\x06proto3"

var (
	file_proto_ateenv_v1_guest_proto_rawDescOnce sync.Once
	file_proto_ateenv_v1_guest_proto_rawDescData []byte
)

func file_proto_ateenv_v1_guest_proto_rawDescGZIP() []byte {
	file_proto_ateenv_v1_guest_proto_rawDescOnce.Do(func() {
		file_proto_ateenv_v1_guest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ateenv_v1_guest_proto_rawDesc), len(file_proto_ateenv_v1_guest_proto_rawDesc)))
	})
	return file_proto_ateenv_v1_guest_proto_rawDescData
}

var file_proto_ateenv_v1_guest_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_ateenv_v1_guest_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_ateenv_v1_guest_proto_goTypes = []any{
	(ProcessStatus)(0),               // 0: ateenv.v1.ProcessStatus
	(LogSource)(0),                   // 1: ateenv.v1.LogSource
	(*Process)(nil),                  // 2: ateenv.v1.Process
	(*StartProcessRequest)(nil),      // 3: ateenv.v1.StartProcessRequest
	(*StartProcessResponse)(nil),     // 4: ateenv.v1.StartProcessResponse
	(*GetProcessRequest)(nil),        // 5: ateenv.v1.GetProcessRequest
	(*StreamProcessLogsRequest)(nil), // 6: ateenv.v1.StreamProcessLogsRequest
	(*ProcessLogChunk)(nil),          // 7: ateenv.v1.ProcessLogChunk
	(*KillProcessRequest)(nil),       // 8: ateenv.v1.KillProcessRequest
	(*KillProcessResponse)(nil),      // 9: ateenv.v1.KillProcessResponse
	(*ReadFileRequest)(nil),          // 10: ateenv.v1.ReadFileRequest
	(*FileChunk)(nil),                // 11: ateenv.v1.FileChunk
	(*WriteFileRequest)(nil),         // 12: ateenv.v1.WriteFileRequest
	(*WriteFileResponse)(nil),        // 13: ateenv.v1.WriteFileResponse
	nil,                              // 14: ateenv.v1.StartProcessRequest.EnvEntry
	(*timestamppb.Timestamp)(nil),    // 15: google.protobuf.Timestamp
}
var file_proto_ateenv_v1_guest_proto_depIdxs = []int32{
	0,  // 0: ateenv.v1.Process.status:type_name -> ateenv.v1.ProcessStatus
	15, // 1: ateenv.v1.Process.started_at:type_name -> google.protobuf.Timestamp
	15, // 2: ateenv.v1.Process.finished_at:type_name -> google.protobuf.Timestamp
	14, // 3: ateenv.v1.StartProcessRequest.env:type_name -> ateenv.v1.StartProcessRequest.EnvEntry
	1,  // 4: ateenv.v1.ProcessLogChunk.source:type_name -> ateenv.v1.LogSource
	3,  // 5: ateenv.v1.ProcessService.StartProcess:input_type -> ateenv.v1.StartProcessRequest
	5,  // 6: ateenv.v1.ProcessService.GetProcess:input_type -> ateenv.v1.GetProcessRequest
	6,  // 7: ateenv.v1.ProcessService.StreamProcessLogs:input_type -> ateenv.v1.StreamProcessLogsRequest
	8,  // 8: ateenv.v1.ProcessService.KillProcess:input_type -> ateenv.v1.KillProcessRequest
	10, // 9: ateenv.v1.FileSystemService.ReadFile:input_type -> ateenv.v1.ReadFileRequest
	12, // 10: ateenv.v1.FileSystemService.WriteFile:input_type -> ateenv.v1.WriteFileRequest
	4,  // 11: ateenv.v1.ProcessService.StartProcess:output_type -> ateenv.v1.StartProcessResponse
	2,  // 12: ateenv.v1.ProcessService.GetProcess:output_type -> ateenv.v1.Process
	7,  // 13: ateenv.v1.ProcessService.StreamProcessLogs:output_type -> ateenv.v1.ProcessLogChunk
	9,  // 14: ateenv.v1.ProcessService.KillProcess:output_type -> ateenv.v1.KillProcessResponse
	11, // 15: ateenv.v1.FileSystemService.ReadFile:output_type -> ateenv.v1.FileChunk
	13, // 16: ateenv.v1.FileSystemService.WriteFile:output_type -> ateenv.v1.WriteFileResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_ateenv_v1_guest_proto_init() }
func file_proto_ateenv_v1_guest_proto_init() {
	if File_proto_ateenv_v1_guest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ateenv_v1_guest_proto_rawDesc), len(file_proto_ateenv_v1_guest_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_ateenv_v1_guest_proto_goTypes,
		DependencyIndexes: file_proto_ateenv_v1_guest_proto_depIdxs,
		EnumInfos:         file_proto_ateenv_v1_guest_proto_enumTypes,
		MessageInfos:      file_proto_ateenv_v1_guest_proto_msgTypes,
	}.Build()
	File_proto_ateenv_v1_guest_proto = out.File
	file_proto_ateenv_v1_guest_proto_goTypes = nil
	file_proto_ateenv_v1_guest_proto_depIdxs = nil
}
