// Copyright 2026 The Agent Substrate Authors.
//
// Minimal Protocol Buffers definition for the Agent Substrate Guest Data Plane.
// Exposes basic process execution (async lifecycle) and file read/write.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: proto/ateenv/v1/guest.proto

package ateenvv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status of an asynchronous process execution.
type ProcessStatus int32

const (
	ProcessStatus_PROCESS_STATUS_UNSPECIFIED ProcessStatus = 0
	// Process is actively running in the background.
	ProcessStatus_PROCESS_STATUS_RUNNING ProcessStatus = 1
	// Process completed successfully with exit code 0.
	ProcessStatus_PROCESS_STATUS_COMPLETED ProcessStatus = 2
	// Process completed with a non-zero exit code or failed to run.
	ProcessStatus_PROCESS_STATUS_FAILED ProcessStatus = 3
	// Process was killed before completion.
	ProcessStatus_PROCESS_STATUS_TERMINATED ProcessStatus = 4
)

// Enum value maps for ProcessStatus.
var (
	ProcessStatus_name = map[int32]string{
		0: "PROCESS_STATUS_UNSPECIFIED",
		1: "PROCESS_STATUS_RUNNING",
		2: "PROCESS_STATUS_COMPLETED",
		3: "PROCESS_STATUS_FAILED",
		4: "PROCESS_STATUS_TERMINATED",
	}
	ProcessStatus_value = map[string]int32{
		"PROCESS_STATUS_UNSPECIFIED": 0,
		"PROCESS_STATUS_RUNNING":     1,
		"PROCESS_STATUS_COMPLETED":   2,
		"PROCESS_STATUS_FAILED":      3,
		"PROCESS_STATUS_TERMINATED":  4,
	}
)

func (x ProcessStatus) Enum() *ProcessStatus {
	p := new(ProcessStatus)
	*p = x
	return p
}

func (x ProcessStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ateenv_v1_guest_proto_enumTypes[0].Descriptor()
}

func (ProcessStatus) Type() protoreflect.EnumType {
	return &file_proto_ateenv_v1_guest_proto_enumTypes[0]
}

func (x ProcessStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessStatus.Descriptor instead.
func (ProcessStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_ateenv_v1_guest_proto_rawDescGZIP(), []int{0}
}

// Request to start a background asynchronous process.
type StartProcessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command binary and arguments to execute (e.g. ["pytest", "tests/"] or ["sh", "-c", "ls -la"]).
	Command []string `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	// Working directory inside the container (defaults to container workdir).
	Cwd string `protobuf:"bytes,2,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// Environment variables to set for the background process.
	Env           map[string]string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProcessRequest) Reset() {
	*x = StartProcessRequest{}
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessRequest) ProtoMessage() {}

func (x *StartProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessRequest.ProtoReflect.Descriptor instead.
func (*StartProcessRequest) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1_guest_proto_rawDescGZIP(), []int{0}
}

func (x *StartProcessRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *StartProcessRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *StartProcessRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

// Response returned immediately after launching an asynchronous process.
type StartProcessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique process identifier used for polling status, reading logs, and killing.
	ProcessId     string `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProcessResponse) Reset() {
	*x = StartProcessResponse{}
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessResponse) ProtoMessage() {}

func (x *StartProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessResponse.ProtoReflect.Descriptor instead.
func (*StartProcessResponse) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1_guest_proto_rawDescGZIP(), []int{1}
}

func (x *StartProcessResponse) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

// Request to check status and read output of an asynchronous process.
type GetProcessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the process to inspect.
	ProcessId string `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	// Byte offset to start reading stdout from (enables incremental log polling).
	StdoutOffset int64 `protobuf:"varint,2,opt,name=stdout_offset,json=stdoutOffset,proto3" json:"stdout_offset,omitempty"`
	// Byte offset to start reading stderr from (enables incremental log polling).
	StderrOffset  int64 `protobuf:"varint,3,opt,name=stderr_offset,json=stderrOffset,proto3" json:"stderr_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessRequest) Reset() {
	*x = GetProcessRequest{}
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessRequest) ProtoMessage() {}

func (x *GetProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessRequest.ProtoReflect.Descriptor instead.
func (*GetProcessRequest) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1_guest_proto_rawDescGZIP(), []int{2}
}

func (x *GetProcessRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *GetProcessRequest) GetStdoutOffset() int64 {
	if x != nil {
		return x.StdoutOffset
	}
	return 0
}

func (x *GetProcessRequest) GetStderrOffset() int64 {
	if x != nil {
		return x.StderrOffset
	}
	return 0
}

// Response containing execution status and output logs.
type GetProcessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current execution lifecycle state of the process.
	Status ProcessStatus `protobuf:"varint,1,opt,name=status,proto3,enum=ateenv.v1.ProcessStatus" json:"status,omitempty"`
	// Process exit code (valid once status is COMPLETED, FAILED, or TERMINATED).
	ExitCode int32 `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Captured standard output text since the requested stdout_offset.
	Stdout string `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// Captured standard error text since the requested stderr_offset.
	Stderr string `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	// Total byte size of all stdout generated by the process so far.
	TotalStdoutBytes int64 `protobuf:"varint,5,opt,name=total_stdout_bytes,json=totalStdoutBytes,proto3" json:"total_stdout_bytes,omitempty"`
	// Total byte size of all stderr generated by the process so far.
	TotalStderrBytes int64 `protobuf:"varint,6,opt,name=total_stderr_bytes,json=totalStderrBytes,proto3" json:"total_stderr_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetProcessResponse) Reset() {
	*x = GetProcessResponse{}
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessResponse) ProtoMessage() {}

func (x *GetProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessResponse.ProtoReflect.Descriptor instead.
func (*GetProcessResponse) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1_guest_proto_rawDescGZIP(), []int{3}
}

func (x *GetProcessResponse) GetStatus() ProcessStatus {
	if x != nil {
		return x.Status
	}
	return ProcessStatus_PROCESS_STATUS_UNSPECIFIED
}

func (x *GetProcessResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *GetProcessResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *GetProcessResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *GetProcessResponse) GetTotalStdoutBytes() int64 {
	if x != nil {
		return x.TotalStdoutBytes
	}
	return 0
}

func (x *GetProcessResponse) GetTotalStderrBytes() int64 {
	if x != nil {
		return x.TotalStderrBytes
	}
	return 0
}

// Request to terminate a running asynchronous process.
type KillProcessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the background process to terminate.
	ProcessId     string `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillProcessRequest) Reset() {
	*x = KillProcessRequest{}
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillProcessRequest) ProtoMessage() {}

func (x *KillProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillProcessRequest.ProtoReflect.Descriptor instead.
func (*KillProcessRequest) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1_guest_proto_rawDescGZIP(), []int{4}
}

func (x *KillProcessRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

// Response from terminating a process.
type KillProcessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exit status code after process termination.
	ExitCode      int32 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillProcessResponse) Reset() {
	*x = KillProcessResponse{}
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillProcessResponse) ProtoMessage() {}

func (x *KillProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillProcessResponse.ProtoReflect.Descriptor instead.
func (*KillProcessResponse) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1_guest_proto_rawDescGZIP(), []int{5}
}

func (x *KillProcessResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

// Request to read a file from the container.
type ReadFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute or workspace-relative path of the file to read.
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1_guest_proto_rawDescGZIP(), []int{6}
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Response containing the file data.
type ReadFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw binary or text contents of the file.
	Content       []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1_guest_proto_rawDescGZIP(), []int{7}
}

func (x *ReadFileResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// Request to write data to a file in the container.
type WriteFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute or workspace-relative path of the file to write.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Raw binary or text contents to write to the file.
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Optional POSIX file mode permission (e.g. 0644 or 0755). If 0, defaults to 0644.
	Mode          uint32 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1_guest_proto_rawDescGZIP(), []int{8}
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *WriteFileRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// Response confirming the write operation.
type WriteFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of bytes written to the file.
	BytesWritten  int64 `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1_guest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1_guest_proto_rawDescGZIP(), []int{9}
}

func (x *WriteFileResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

var File_proto_ateenv_v1_guest_proto protoreflect.FileDescriptor

const file_proto_ateenv_v1_guest_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/ateenv/v1/guest.proto\x12\tateenv.v1\"\xb4\x01\n" +
	"\x13StartProcessRequest\x12\x18\n" +
	"\acommand\x18\x01 \x03(\tR\acommand\x12\x10\n" +
	"\x03cwd\x18\x02 \x01(\tR\x03cwd\x129\n" +
	"\x03env\x18\x03 \x03(\v2'.ateenv.v1.StartProcessRequest.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"5\n" +
	"\x14StartProcessResponse\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\"|\n" +
	"\x11GetProcessRequest\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12#\n" +
	"\rstdout_offset\x18\x02 \x01(\x03R\fstdoutOffset\x12#\n" +
	"\rstderr_offset\x18\x03 \x01(\x03R\fstderrOffset\"\xef\x01\n" +
	"\x12GetProcessResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.ateenv.v1.ProcessStatusR\x06status\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\x12,\n" +
	"\x12total_stdout_bytes\x18\x05 \x01(\x03R\x10totalStdoutBytes\x12,\n" +
	"\x12total_stderr_bytes\x18\x06 \x01(\x03R\x10totalStderrBytes\"3\n" +
	"\x12KillProcessRequest\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\"2\n" +
	"\x13KillProcessResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\"%\n" +
	"\x0fReadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\",\n" +
	"\x10ReadFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"T\n" +
	"\x10WriteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\"8\n" +
	"\x11WriteFileResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x03R\fbytesWritten*\xa3\x01\n" +
	"\rProcessStatus\x12\x1e\n" +
	"\x1aPROCESS_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PROCESS_STATUS_RUNNING\x10\x01\x12\x1c\n" +
	"\x18PROCESS_STATUS_COMPLETED\x10\x02\x12\x19\n" +
	"\x15PROCESS_STATUS_FAILED\x10\x03\x12\x1d\n" +
	"\x19PROCESS_STATUS_TERMINATED\x10\x042\xfa\x01\n" +
	"\x0eProcessService\x12O\n" +
	"\fStartProcess\x12\x1e.ateenv.v1.StartProcessRequest\x1a\x1f.ateenv.v1.StartProcessResponse\x12I\n" +
	"\n" +
	"GetProcess\x12\x1c.ateenv.v1.GetProcessRequest\x1a\x1d.ateenv.v1.GetProcessResponse\x12L\n" +
	"\vKillProcess\x12\x1d.ateenv.v1.KillProcessRequest\x1a\x1e.ateenv.v1.KillProcessResponse2\xa0\x01\n" +
	"\x11FileSystemService\x12C\n" +
	"\bReadFile\x12\x1a.ateenv.v1.ReadFileRequest\x1a\x1b.ateenv.v1.ReadFileResponse\x12F\n" +
	"\tWriteFile\x12\x1b.ateenv.v1.WriteFileRequest\x1a\x1c.ateenv.v1.WriteFileResponseB9Z7github.com/agent-substrate/env/proto/ateenv/v1;ateenvv1b\x06proto3"

var (
	file_proto_ateenv_v1_guest_proto_rawDescOnce sync.Once
	file_proto_ateenv_v1_guest_proto_rawDescData []byte
)

func file_proto_ateenv_v1_guest_proto_rawDescGZIP() []byte {
	file_proto_ateenv_v1_guest_proto_rawDescOnce.Do(func() {
		file_proto_ateenv_v1_guest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ateenv_v1_guest_proto_rawDesc), len(file_proto_ateenv_v1_guest_proto_rawDesc)))
	})
	return file_proto_ateenv_v1_guest_proto_rawDescData
}

var file_proto_ateenv_v1_guest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_ateenv_v1_guest_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_ateenv_v1_guest_proto_goTypes = []any{
	(ProcessStatus)(0),           // 0: ateenv.v1.ProcessStatus
	(*StartProcessRequest)(nil),  // 1: ateenv.v1.StartProcessRequest
	(*StartProcessResponse)(nil), // 2: ateenv.v1.StartProcessResponse
	(*GetProcessRequest)(nil),    // 3: ateenv.v1.GetProcessRequest
	(*GetProcessResponse)(nil),   // 4: ateenv.v1.GetProcessResponse
	(*KillProcessRequest)(nil),   // 5: ateenv.v1.KillProcessRequest
	(*KillProcessResponse)(nil),  // 6: ateenv.v1.KillProcessResponse
	(*ReadFileRequest)(nil),      // 7: ateenv.v1.ReadFileRequest
	(*ReadFileResponse)(nil),     // 8: ateenv.v1.ReadFileResponse
	(*WriteFileRequest)(nil),     // 9: ateenv.v1.WriteFileRequest
	(*WriteFileResponse)(nil),    // 10: ateenv.v1.WriteFileResponse
	nil,                          // 11: ateenv.v1.StartProcessRequest.EnvEntry
}
var file_proto_ateenv_v1_guest_proto_depIdxs = []int32{
	11, // 0: ateenv.v1.StartProcessRequest.env:type_name -> ateenv.v1.StartProcessRequest.EnvEntry
	0,  // 1: ateenv.v1.GetProcessResponse.status:type_name -> ateenv.v1.ProcessStatus
	1,  // 2: ateenv.v1.ProcessService.StartProcess:input_type -> ateenv.v1.StartProcessRequest
	3,  // 3: ateenv.v1.ProcessService.GetProcess:input_type -> ateenv.v1.GetProcessRequest
	5,  // 4: ateenv.v1.ProcessService.KillProcess:input_type -> ateenv.v1.KillProcessRequest
	7,  // 5: ateenv.v1.FileSystemService.ReadFile:input_type -> ateenv.v1.ReadFileRequest
	9,  // 6: ateenv.v1.FileSystemService.WriteFile:input_type -> ateenv.v1.WriteFileRequest
	2,  // 7: ateenv.v1.ProcessService.StartProcess:output_type -> ateenv.v1.StartProcessResponse
	4,  // 8: ateenv.v1.ProcessService.GetProcess:output_type -> ateenv.v1.GetProcessResponse
	6,  // 9: ateenv.v1.ProcessService.KillProcess:output_type -> ateenv.v1.KillProcessResponse
	8,  // 10: ateenv.v1.FileSystemService.ReadFile:output_type -> ateenv.v1.ReadFileResponse
	10, // 11: ateenv.v1.FileSystemService.WriteFile:output_type -> ateenv.v1.WriteFileResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ateenv_v1_guest_proto_init() }
func file_proto_ateenv_v1_guest_proto_init() {
	if File_proto_ateenv_v1_guest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ateenv_v1_guest_proto_rawDesc), len(file_proto_ateenv_v1_guest_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_ateenv_v1_guest_proto_goTypes,
		DependencyIndexes: file_proto_ateenv_v1_guest_proto_depIdxs,
		EnumInfos:         file_proto_ateenv_v1_guest_proto_enumTypes,
		MessageInfos:      file_proto_ateenv_v1_guest_proto_msgTypes,
	}.Build()
	File_proto_ateenv_v1_guest_proto = out.File
	file_proto_ateenv_v1_guest_proto_goTypes = nil
	file_proto_ateenv_v1_guest_proto_depIdxs = nil
}
