// Copyright 2026 The Agent Substrate Authors.
//
// Protocol Buffers definition for the Agent Substrate Environment Control Plane API.
// Exposes environment lifecycle operations (create, get, suspend, delete).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: proto/ateenv/v1alpha/env.proto

package ateenvv1alpha

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle status of an environment, matching Substrate actor statuses.
type EnvironmentStatus int32

const (
	EnvironmentStatus_ENVIRONMENT_STATUS_UNSPECIFIED EnvironmentStatus = 0
	// Environment is resuming / warming up from snapshot.
	EnvironmentStatus_ENVIRONMENT_STATUS_RESUMING EnvironmentStatus = 1
	// Environment is active and ready to accept operations.
	EnvironmentStatus_ENVIRONMENT_STATUS_RUNNING EnvironmentStatus = 2
	// Environment is in the process of suspending.
	EnvironmentStatus_ENVIRONMENT_STATUS_SUSPENDING EnvironmentStatus = 3
	// Environment is suspended and checkpointed.
	EnvironmentStatus_ENVIRONMENT_STATUS_SUSPENDED EnvironmentStatus = 4
	// Environment is in the process of pausing.
	EnvironmentStatus_ENVIRONMENT_STATUS_PAUSING EnvironmentStatus = 5
	// Environment is paused.
	EnvironmentStatus_ENVIRONMENT_STATUS_PAUSED EnvironmentStatus = 6
	// Environment process crashed.
	EnvironmentStatus_ENVIRONMENT_STATUS_CRASHED EnvironmentStatus = 7
	// Environment is being deleted.
	EnvironmentStatus_ENVIRONMENT_STATUS_DELETING EnvironmentStatus = 8
)

// Enum value maps for EnvironmentStatus.
var (
	EnvironmentStatus_name = map[int32]string{
		0: "ENVIRONMENT_STATUS_UNSPECIFIED",
		1: "ENVIRONMENT_STATUS_RESUMING",
		2: "ENVIRONMENT_STATUS_RUNNING",
		3: "ENVIRONMENT_STATUS_SUSPENDING",
		4: "ENVIRONMENT_STATUS_SUSPENDED",
		5: "ENVIRONMENT_STATUS_PAUSING",
		6: "ENVIRONMENT_STATUS_PAUSED",
		7: "ENVIRONMENT_STATUS_CRASHED",
		8: "ENVIRONMENT_STATUS_DELETING",
	}
	EnvironmentStatus_value = map[string]int32{
		"ENVIRONMENT_STATUS_UNSPECIFIED": 0,
		"ENVIRONMENT_STATUS_RESUMING":    1,
		"ENVIRONMENT_STATUS_RUNNING":     2,
		"ENVIRONMENT_STATUS_SUSPENDING":  3,
		"ENVIRONMENT_STATUS_SUSPENDED":   4,
		"ENVIRONMENT_STATUS_PAUSING":     5,
		"ENVIRONMENT_STATUS_PAUSED":      6,
		"ENVIRONMENT_STATUS_CRASHED":     7,
		"ENVIRONMENT_STATUS_DELETING":    8,
	}
)

func (x EnvironmentStatus) Enum() *EnvironmentStatus {
	p := new(EnvironmentStatus)
	*p = x
	return p
}

func (x EnvironmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnvironmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ateenv_v1alpha_env_proto_enumTypes[0].Descriptor()
}

func (EnvironmentStatus) Type() protoreflect.EnumType {
	return &file_proto_ateenv_v1alpha_env_proto_enumTypes[0]
}

func (x EnvironmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnvironmentStatus.Descriptor instead.
func (EnvironmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_ateenv_v1alpha_env_proto_rawDescGZIP(), []int{0}
}

// Template represents an ActorTemplate used to instantiate environments.
type Template struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the ActorTemplate (e.g. "default-env").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Substrate atespace where the ActorTemplate is located.
	Atespace      string `protobuf:"bytes,2,opt,name=atespace,proto3" json:"atespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Template) Reset() {
	*x = Template{}
	mi := &file_proto_ateenv_v1alpha_env_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template) ProtoMessage() {}

func (x *Template) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1alpha_env_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template.ProtoReflect.Descriptor instead.
func (*Template) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1alpha_env_proto_rawDescGZIP(), []int{0}
}

func (x *Template) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Template) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

// Environment represents an isolated execution environment backed by a Substrate actor.
type Environment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique environment identifier (DNS-1123 label).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Substrate atespace where the environment actor lives.
	Atespace string `protobuf:"bytes,2,opt,name=atespace,proto3" json:"atespace,omitempty"`
	// ActorTemplate configuration the environment is instantiated from.
	Template *Template `protobuf:"bytes,3,opt,name=template,proto3" json:"template,omitempty"`
	// Current lifecycle status of the environment.
	Status        EnvironmentStatus `protobuf:"varint,4,opt,name=status,proto3,enum=ateenv.v1alpha.EnvironmentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Environment) Reset() {
	*x = Environment{}
	mi := &file_proto_ateenv_v1alpha_env_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Environment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Environment) ProtoMessage() {}

func (x *Environment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1alpha_env_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Environment.ProtoReflect.Descriptor instead.
func (*Environment) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1alpha_env_proto_rawDescGZIP(), []int{1}
}

func (x *Environment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Environment) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *Environment) GetTemplate() *Template {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *Environment) GetStatus() EnvironmentStatus {
	if x != nil {
		return x.Status
	}
	return EnvironmentStatus_ENVIRONMENT_STATUS_UNSPECIFIED
}

// Request to create and start a new environment.
type CreateEnvironmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique environment identifier (DNS-1123 label). Required.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Substrate atespace for the environment (defaults to "default").
	Atespace string `protobuf:"bytes,2,opt,name=atespace,proto3" json:"atespace,omitempty"`
	// ActorTemplate configuration to instantiate (defaults to name "default-env" in atespace "default").
	Template      *Template `protobuf:"bytes,3,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnvironmentRequest) Reset() {
	*x = CreateEnvironmentRequest{}
	mi := &file_proto_ateenv_v1alpha_env_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnvironmentRequest) ProtoMessage() {}

func (x *CreateEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1alpha_env_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*CreateEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1alpha_env_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEnvironmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateEnvironmentRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *CreateEnvironmentRequest) GetTemplate() *Template {
	if x != nil {
		return x.Template
	}
	return nil
}

// Response returned after creating an environment.
type CreateEnvironmentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created environment.
	Environment   *Environment `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnvironmentResponse) Reset() {
	*x = CreateEnvironmentResponse{}
	mi := &file_proto_ateenv_v1alpha_env_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnvironmentResponse) ProtoMessage() {}

func (x *CreateEnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1alpha_env_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnvironmentResponse.ProtoReflect.Descriptor instead.
func (*CreateEnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1alpha_env_proto_rawDescGZIP(), []int{3}
}

func (x *CreateEnvironmentResponse) GetEnvironment() *Environment {
	if x != nil {
		return x.Environment
	}
	return nil
}

// Request to inspect an environment.
type GetEnvironmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the environment to retrieve. Required.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Substrate atespace of the environment (defaults to "default").
	Atespace      string `protobuf:"bytes,2,opt,name=atespace,proto3" json:"atespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvironmentRequest) Reset() {
	*x = GetEnvironmentRequest{}
	mi := &file_proto_ateenv_v1alpha_env_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvironmentRequest) ProtoMessage() {}

func (x *GetEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1alpha_env_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*GetEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1alpha_env_proto_rawDescGZIP(), []int{4}
}

func (x *GetEnvironmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetEnvironmentRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

// Response containing environment details.
type GetEnvironmentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested environment.
	Environment   *Environment `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvironmentResponse) Reset() {
	*x = GetEnvironmentResponse{}
	mi := &file_proto_ateenv_v1alpha_env_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvironmentResponse) ProtoMessage() {}

func (x *GetEnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1alpha_env_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvironmentResponse.ProtoReflect.Descriptor instead.
func (*GetEnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1alpha_env_proto_rawDescGZIP(), []int{5}
}

func (x *GetEnvironmentResponse) GetEnvironment() *Environment {
	if x != nil {
		return x.Environment
	}
	return nil
}

// Request to suspend an environment.
type SuspendEnvironmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the environment to suspend. Required.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Substrate atespace of the environment (defaults to "default").
	Atespace      string `protobuf:"bytes,2,opt,name=atespace,proto3" json:"atespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendEnvironmentRequest) Reset() {
	*x = SuspendEnvironmentRequest{}
	mi := &file_proto_ateenv_v1alpha_env_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendEnvironmentRequest) ProtoMessage() {}

func (x *SuspendEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1alpha_env_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*SuspendEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1alpha_env_proto_rawDescGZIP(), []int{6}
}

func (x *SuspendEnvironmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SuspendEnvironmentRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

// Response returned after suspending an environment.
type SuspendEnvironmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendEnvironmentResponse) Reset() {
	*x = SuspendEnvironmentResponse{}
	mi := &file_proto_ateenv_v1alpha_env_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendEnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendEnvironmentResponse) ProtoMessage() {}

func (x *SuspendEnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1alpha_env_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendEnvironmentResponse.ProtoReflect.Descriptor instead.
func (*SuspendEnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1alpha_env_proto_rawDescGZIP(), []int{7}
}

// Request to delete an environment.
type DeleteEnvironmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the environment to delete. Required.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Substrate atespace of the environment (defaults to "default").
	Atespace      string `protobuf:"bytes,2,opt,name=atespace,proto3" json:"atespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEnvironmentRequest) Reset() {
	*x = DeleteEnvironmentRequest{}
	mi := &file_proto_ateenv_v1alpha_env_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEnvironmentRequest) ProtoMessage() {}

func (x *DeleteEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1alpha_env_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1alpha_env_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteEnvironmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteEnvironmentRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

// Response returned after deleting an environment.
type DeleteEnvironmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEnvironmentResponse) Reset() {
	*x = DeleteEnvironmentResponse{}
	mi := &file_proto_ateenv_v1alpha_env_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEnvironmentResponse) ProtoMessage() {}

func (x *DeleteEnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ateenv_v1alpha_env_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEnvironmentResponse.ProtoReflect.Descriptor instead.
func (*DeleteEnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_ateenv_v1alpha_env_proto_rawDescGZIP(), []int{9}
}

var File_proto_ateenv_v1alpha_env_proto protoreflect.FileDescriptor

const file_proto_ateenv_v1alpha_env_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/ateenv/v1alpha/env.proto\x12\x0eateenv.v1alpha\":\n" +
	"\bTemplate\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\batespace\x18\x02 \x01(\tR\batespace\"\xaa\x01\n" +
	"\vEnvironment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\batespace\x18\x02 \x01(\tR\batespace\x124\n" +
	"\btemplate\x18\x03 \x01(\v2\x18.ateenv.v1alpha.TemplateR\btemplate\x129\n" +
	"\x06status\x18\x04 \x01(\x0e2!.ateenv.v1alpha.EnvironmentStatusR\x06status\"|\n" +
	"\x18CreateEnvironmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\batespace\x18\x02 \x01(\tR\batespace\x124\n" +
	"\btemplate\x18\x03 \x01(\v2\x18.ateenv.v1alpha.TemplateR\btemplate\"Z\n" +
	"\x19CreateEnvironmentResponse\x12=\n" +
	"\venvironment\x18\x01 \x01(\v2\x1b.ateenv.v1alpha.EnvironmentR\venvironment\"C\n" +
	"\x15GetEnvironmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\batespace\x18\x02 \x01(\tR\batespace\"W\n" +
	"\x16GetEnvironmentResponse\x12=\n" +
	"\venvironment\x18\x01 \x01(\v2\x1b.ateenv.v1alpha.EnvironmentR\venvironment\"G\n" +
	"\x19SuspendEnvironmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\batespace\x18\x02 \x01(\tR\batespace\"\x1c\n" +
	"\x1aSuspendEnvironmentResponse\"F\n" +
	"\x18DeleteEnvironmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\batespace\x18\x02 \x01(\tR\batespace\"\x1b\n" +
	"\x19DeleteEnvironmentResponse*\xbd\x02\n" +
	"\x11EnvironmentStatus\x12\"\n" +
	"\x1eENVIRONMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bENVIRONMENT_STATUS_RESUMING\x10\x01\x12\x1e\n" +
	"\x1aENVIRONMENT_STATUS_RUNNING\x10\x02\x12!\n" +
	"\x1dENVIRONMENT_STATUS_SUSPENDING\x10\x03\x12 \n" +
	"\x1cENVIRONMENT_STATUS_SUSPENDED\x10\x04\x12\x1e\n" +
	"\x1aENVIRONMENT_STATUS_PAUSING\x10\x05\x12\x1d\n" +
	"\x19ENVIRONMENT_STATUS_PAUSED\x10\x06\x12\x1e\n" +
	"\x1aENVIRONMENT_STATUS_CRASHED\x10\a\x12\x1f\n" +
	"\x1bENVIRONMENT_STATUS_DELETING\x10\b2\xb6\x03\n" +
	"\x12EnvironmentService\x12h\n" +
	"\x11CreateEnvironment\x12(.ateenv.v1alpha.CreateEnvironmentRequest\x1a).ateenv.v1alpha.CreateEnvironmentResponse\x12_\n" +
	"\x0eGetEnvironment\x12%.ateenv.v1alpha.GetEnvironmentRequest\x1a&.ateenv.v1alpha.GetEnvironmentResponse\x12k\n" +
	"\x12SuspendEnvironment\x12).ateenv.v1alpha.SuspendEnvironmentRequest\x1a*.ateenv.v1alpha.SuspendEnvironmentResponse\x12h\n" +
	"\x11DeleteEnvironment\x12(.ateenv.v1alpha.DeleteEnvironmentRequest\x1a).ateenv.v1alpha.DeleteEnvironmentResponseBCZAgithub.com/agent-substrate/env/proto/ateenv/v1alpha;ateenvv1alphab\x06proto3"

var (
	file_proto_ateenv_v1alpha_env_proto_rawDescOnce sync.Once
	file_proto_ateenv_v1alpha_env_proto_rawDescData []byte
)

func file_proto_ateenv_v1alpha_env_proto_rawDescGZIP() []byte {
	file_proto_ateenv_v1alpha_env_proto_rawDescOnce.Do(func() {
		file_proto_ateenv_v1alpha_env_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ateenv_v1alpha_env_proto_rawDesc), len(file_proto_ateenv_v1alpha_env_proto_rawDesc)))
	})
	return file_proto_ateenv_v1alpha_env_proto_rawDescData
}

var file_proto_ateenv_v1alpha_env_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_ateenv_v1alpha_env_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_ateenv_v1alpha_env_proto_goTypes = []any{
	(EnvironmentStatus)(0),             // 0: ateenv.v1alpha.EnvironmentStatus
	(*Template)(nil),                   // 1: ateenv.v1alpha.Template
	(*Environment)(nil),                // 2: ateenv.v1alpha.Environment
	(*CreateEnvironmentRequest)(nil),   // 3: ateenv.v1alpha.CreateEnvironmentRequest
	(*CreateEnvironmentResponse)(nil),  // 4: ateenv.v1alpha.CreateEnvironmentResponse
	(*GetEnvironmentRequest)(nil),      // 5: ateenv.v1alpha.GetEnvironmentRequest
	(*GetEnvironmentResponse)(nil),     // 6: ateenv.v1alpha.GetEnvironmentResponse
	(*SuspendEnvironmentRequest)(nil),  // 7: ateenv.v1alpha.SuspendEnvironmentRequest
	(*SuspendEnvironmentResponse)(nil), // 8: ateenv.v1alpha.SuspendEnvironmentResponse
	(*DeleteEnvironmentRequest)(nil),   // 9: ateenv.v1alpha.DeleteEnvironmentRequest
	(*DeleteEnvironmentResponse)(nil),  // 10: ateenv.v1alpha.DeleteEnvironmentResponse
}
var file_proto_ateenv_v1alpha_env_proto_depIdxs = []int32{
	1,  // 0: ateenv.v1alpha.Environment.template:type_name -> ateenv.v1alpha.Template
	0,  // 1: ateenv.v1alpha.Environment.status:type_name -> ateenv.v1alpha.EnvironmentStatus
	1,  // 2: ateenv.v1alpha.CreateEnvironmentRequest.template:type_name -> ateenv.v1alpha.Template
	2,  // 3: ateenv.v1alpha.CreateEnvironmentResponse.environment:type_name -> ateenv.v1alpha.Environment
	2,  // 4: ateenv.v1alpha.GetEnvironmentResponse.environment:type_name -> ateenv.v1alpha.Environment
	3,  // 5: ateenv.v1alpha.EnvironmentService.CreateEnvironment:input_type -> ateenv.v1alpha.CreateEnvironmentRequest
	5,  // 6: ateenv.v1alpha.EnvironmentService.GetEnvironment:input_type -> ateenv.v1alpha.GetEnvironmentRequest
	7,  // 7: ateenv.v1alpha.EnvironmentService.SuspendEnvironment:input_type -> ateenv.v1alpha.SuspendEnvironmentRequest
	9,  // 8: ateenv.v1alpha.EnvironmentService.DeleteEnvironment:input_type -> ateenv.v1alpha.DeleteEnvironmentRequest
	4,  // 9: ateenv.v1alpha.EnvironmentService.CreateEnvironment:output_type -> ateenv.v1alpha.CreateEnvironmentResponse
	6,  // 10: ateenv.v1alpha.EnvironmentService.GetEnvironment:output_type -> ateenv.v1alpha.GetEnvironmentResponse
	8,  // 11: ateenv.v1alpha.EnvironmentService.SuspendEnvironment:output_type -> ateenv.v1alpha.SuspendEnvironmentResponse
	10, // 12: ateenv.v1alpha.EnvironmentService.DeleteEnvironment:output_type -> ateenv.v1alpha.DeleteEnvironmentResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_ateenv_v1alpha_env_proto_init() }
func file_proto_ateenv_v1alpha_env_proto_init() {
	if File_proto_ateenv_v1alpha_env_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ateenv_v1alpha_env_proto_rawDesc), len(file_proto_ateenv_v1alpha_env_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ateenv_v1alpha_env_proto_goTypes,
		DependencyIndexes: file_proto_ateenv_v1alpha_env_proto_depIdxs,
		EnumInfos:         file_proto_ateenv_v1alpha_env_proto_enumTypes,
		MessageInfos:      file_proto_ateenv_v1alpha_env_proto_msgTypes,
	}.Build()
	File_proto_ateenv_v1alpha_env_proto = out.File
	file_proto_ateenv_v1alpha_env_proto_goTypes = nil
	file_proto_ateenv_v1alpha_env_proto_depIdxs = nil
}
