// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Copyright 2026 The Agent Substrate Authors.
//
// Minimal Protocol Buffers definition for the Agent Substrate Guest Data Plane.
// Exposes asynchronous process execution with streaming I/O and signals, and
// streaming file I/O.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ateenv/v1alpha/guest.proto

package ateenvv1alpha

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle state of a process.
type ProcessState int32

const (
	ProcessState_PROCESS_STATE_UNSPECIFIED ProcessState = 0
	// The process is running (or stopped by SIGSTOP) and has not been reaped.
	ProcessState_PROCESS_STATE_RUNNING ProcessState = 1
	// The process has exited; see Process.exit_code.
	ProcessState_PROCESS_STATE_EXITED ProcessState = 2
)

// Enum value maps for ProcessState.
var (
	ProcessState_name = map[int32]string{
		0: "PROCESS_STATE_UNSPECIFIED",
		1: "PROCESS_STATE_RUNNING",
		2: "PROCESS_STATE_EXITED",
	}
	ProcessState_value = map[string]int32{
		"PROCESS_STATE_UNSPECIFIED": 0,
		"PROCESS_STATE_RUNNING":     1,
		"PROCESS_STATE_EXITED":      2,
	}
)

func (x ProcessState) Enum() *ProcessState {
	p := new(ProcessState)
	*p = x
	return p
}

func (x ProcessState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessState) Descriptor() protoreflect.EnumDescriptor {
	return file_ateenv_v1alpha_guest_proto_enumTypes[0].Descriptor()
}

func (ProcessState) Type() protoreflect.EnumType {
	return &file_ateenv_v1alpha_guest_proto_enumTypes[0]
}

func (x ProcessState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessState.Descriptor instead.
func (ProcessState) EnumDescriptor() ([]byte, []int) {
	return file_ateenv_v1alpha_guest_proto_rawDescGZIP(), []int{0}
}

// POSIX signals that can be sent to a process. Values match the Linux signal
// numbers on x86/arm.
type Signal int32

const (
	Signal_SIGNAL_UNSPECIFIED Signal = 0
	Signal_SIGNAL_HUP         Signal = 1
	Signal_SIGNAL_INT         Signal = 2
	Signal_SIGNAL_QUIT        Signal = 3
	Signal_SIGNAL_ILL         Signal = 4
	Signal_SIGNAL_TRAP        Signal = 5
	Signal_SIGNAL_ABRT        Signal = 6
	Signal_SIGNAL_BUS         Signal = 7
	Signal_SIGNAL_FPE         Signal = 8
	Signal_SIGNAL_KILL        Signal = 9
	Signal_SIGNAL_USR1        Signal = 10
	Signal_SIGNAL_SEGV        Signal = 11
	Signal_SIGNAL_USR2        Signal = 12
	Signal_SIGNAL_PIPE        Signal = 13
	Signal_SIGNAL_ALRM        Signal = 14
	Signal_SIGNAL_TERM        Signal = 15
	Signal_SIGNAL_CHLD        Signal = 17
	Signal_SIGNAL_CONT        Signal = 18
	Signal_SIGNAL_STOP        Signal = 19
	Signal_SIGNAL_TSTP        Signal = 20
	Signal_SIGNAL_TTIN        Signal = 21
	Signal_SIGNAL_TTOU        Signal = 22
	Signal_SIGNAL_URG         Signal = 23
	Signal_SIGNAL_XCPU        Signal = 24
	Signal_SIGNAL_XFSZ        Signal = 25
	Signal_SIGNAL_VTALRM      Signal = 26
	Signal_SIGNAL_PROF        Signal = 27
	Signal_SIGNAL_WINCH       Signal = 28
	Signal_SIGNAL_IO          Signal = 29
	Signal_SIGNAL_SYS         Signal = 31
)

// Enum value maps for Signal.
var (
	Signal_name = map[int32]string{
		0:  "SIGNAL_UNSPECIFIED",
		1:  "SIGNAL_HUP",
		2:  "SIGNAL_INT",
		3:  "SIGNAL_QUIT",
		4:  "SIGNAL_ILL",
		5:  "SIGNAL_TRAP",
		6:  "SIGNAL_ABRT",
		7:  "SIGNAL_BUS",
		8:  "SIGNAL_FPE",
		9:  "SIGNAL_KILL",
		10: "SIGNAL_USR1",
		11: "SIGNAL_SEGV",
		12: "SIGNAL_USR2",
		13: "SIGNAL_PIPE",
		14: "SIGNAL_ALRM",
		15: "SIGNAL_TERM",
		17: "SIGNAL_CHLD",
		18: "SIGNAL_CONT",
		19: "SIGNAL_STOP",
		20: "SIGNAL_TSTP",
		21: "SIGNAL_TTIN",
		22: "SIGNAL_TTOU",
		23: "SIGNAL_URG",
		24: "SIGNAL_XCPU",
		25: "SIGNAL_XFSZ",
		26: "SIGNAL_VTALRM",
		27: "SIGNAL_PROF",
		28: "SIGNAL_WINCH",
		29: "SIGNAL_IO",
		31: "SIGNAL_SYS",
	}
	Signal_value = map[string]int32{
		"SIGNAL_UNSPECIFIED": 0,
		"SIGNAL_HUP":         1,
		"SIGNAL_INT":         2,
		"SIGNAL_QUIT":        3,
		"SIGNAL_ILL":         4,
		"SIGNAL_TRAP":        5,
		"SIGNAL_ABRT":        6,
		"SIGNAL_BUS":         7,
		"SIGNAL_FPE":         8,
		"SIGNAL_KILL":        9,
		"SIGNAL_USR1":        10,
		"SIGNAL_SEGV":        11,
		"SIGNAL_USR2":        12,
		"SIGNAL_PIPE":        13,
		"SIGNAL_ALRM":        14,
		"SIGNAL_TERM":        15,
		"SIGNAL_CHLD":        17,
		"SIGNAL_CONT":        18,
		"SIGNAL_STOP":        19,
		"SIGNAL_TSTP":        20,
		"SIGNAL_TTIN":        21,
		"SIGNAL_TTOU":        22,
		"SIGNAL_URG":         23,
		"SIGNAL_XCPU":        24,
		"SIGNAL_XFSZ":        25,
		"SIGNAL_VTALRM":      26,
		"SIGNAL_PROF":        27,
		"SIGNAL_WINCH":       28,
		"SIGNAL_IO":          29,
		"SIGNAL_SYS":         31,
	}
)

func (x Signal) Enum() *Signal {
	p := new(Signal)
	*p = x
	return p
}

func (x Signal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Signal) Descriptor() protoreflect.EnumDescriptor {
	return file_ateenv_v1alpha_guest_proto_enumTypes[1].Descriptor()
}

func (Signal) Type() protoreflect.EnumType {
	return &file_ateenv_v1alpha_guest_proto_enumTypes[1]
}

func (x Signal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Signal.Descriptor instead.
func (Signal) EnumDescriptor() ([]byte, []int) {
	return file_ateenv_v1alpha_guest_proto_rawDescGZIP(), []int{1}
}

// The Process resource: identity, lifecycle state, and exit status.
type Process struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique process identifier assigned by the guest.
	ProcessId string `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	// Command binary and arguments the process was started with.
	Command []string `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	// Operating system PID inside the container.
	Pid int32 `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	// Current lifecycle state.
	State ProcessState `protobuf:"varint,4,opt,name=state,proto3,enum=ateenv.v1alpha.ProcessState" json:"state,omitempty"`
	// Exit status, valid once state is EXITED: the process's exit code, or
	// 128 + signal number if it was terminated by a signal (e.g. 137 for
	// SIGKILL, 143 for SIGTERM).
	ExitCode int32 `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Timestamp when the process started.
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// Timestamp when the process exited. Unset while RUNNING.
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Process) Reset() {
	*x = Process{}
	mi := &file_ateenv_v1alpha_guest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha_guest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha_guest_proto_rawDescGZIP(), []int{0}
}

func (x *Process) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *Process) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Process) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Process) GetState() ProcessState {
	if x != nil {
		return x.State
	}
	return ProcessState_PROCESS_STATE_UNSPECIFIED
}

func (x *Process) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *Process) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Process) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

// Request to start a process.
type StartProcessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command binary and arguments to execute (e.g. ["pytest", "tests/"] or ["sh", "-c", "ls -la"]).
	Command []string `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	// Working directory inside the container (defaults to the guest workspace).
	Cwd string `protobuf:"bytes,2,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// Environment variables to set for the process, on top of the guest's environment.
	Env map[string]string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// If true, stdin is an open pipe fed by WriteProcessInput. If false, stdin
	// reads as empty (/dev/null) and WriteProcessInput is rejected.
	Stdin bool `protobuf:"varint,4,opt,name=stdin,proto3" json:"stdin,omitempty"`
	// Maximum wall-clock run time. On expiry the process group receives SIGKILL.
	// Unset or zero applies the guest's default timeout.
	Timeout       *durationpb.Duration `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProcessRequest) Reset() {
	*x = StartProcessRequest{}
	mi := &file_ateenv_v1alpha_guest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessRequest) ProtoMessage() {}

func (x *StartProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha_guest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessRequest.ProtoReflect.Descriptor instead.
func (*StartProcessRequest) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha_guest_proto_rawDescGZIP(), []int{1}
}

func (x *StartProcessRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *StartProcessRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *StartProcessRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *StartProcessRequest) GetStdin() bool {
	if x != nil {
		return x.Stdin
	}
	return false
}

func (x *StartProcessRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

// Request to get a Process.
type GetProcessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the process to inspect.
	ProcessId     string `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessRequest) Reset() {
	*x = GetProcessRequest{}
	mi := &file_ateenv_v1alpha_guest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessRequest) ProtoMessage() {}

func (x *GetProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha_guest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessRequest.ProtoReflect.Descriptor instead.
func (*GetProcessRequest) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha_guest_proto_rawDescGZIP(), []int{2}
}

func (x *GetProcessRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

// Request to stream output from a process.
type StreamProcessOutputRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the process to stream output from.
	ProcessId string `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	// Byte offset to start reading stdout from (defaults to 0 / beginning).
	// Bytes before the offset are never delivered, so an offset past the end
	// of the spool suppresses stdout entirely.
	StdoutOffset int64 `protobuf:"varint,2,opt,name=stdout_offset,json=stdoutOffset,proto3" json:"stdout_offset,omitempty"`
	// Byte offset to start reading stderr from (defaults to 0 / beginning).
	// Same semantics as stdout_offset.
	StderrOffset int64 `protobuf:"varint,3,opt,name=stderr_offset,json=stderrOffset,proto3" json:"stderr_offset,omitempty"`
	// If true, the stream stays open and delivers new output until the process
	// exits. If false, the output spooled so far is returned and the stream ends.
	Follow        bool `protobuf:"varint,4,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamProcessOutputRequest) Reset() {
	*x = StreamProcessOutputRequest{}
	mi := &file_ateenv_v1alpha_guest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamProcessOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamProcessOutputRequest) ProtoMessage() {}

func (x *StreamProcessOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha_guest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamProcessOutputRequest.ProtoReflect.Descriptor instead.
func (*StreamProcessOutputRequest) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha_guest_proto_rawDescGZIP(), []int{3}
}

func (x *StreamProcessOutputRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *StreamProcessOutputRequest) GetStdoutOffset() int64 {
	if x != nil {
		return x.StdoutOffset
	}
	return 0
}

func (x *StreamProcessOutputRequest) GetStderrOffset() int64 {
	if x != nil {
		return x.StderrOffset
	}
	return 0
}

func (x *StreamProcessOutputRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

// One message on a process output stream. Exactly one field is set.
type ProcessOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Output:
	//
	//	*ProcessOutput_Stdout
	//	*ProcessOutput_Stderr
	//	*ProcessOutput_Exit
	Output        isProcessOutput_Output `protobuf_oneof:"output"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessOutput) Reset() {
	*x = ProcessOutput{}
	mi := &file_ateenv_v1alpha_guest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessOutput) ProtoMessage() {}

func (x *ProcessOutput) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha_guest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessOutput.ProtoReflect.Descriptor instead.
func (*ProcessOutput) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha_guest_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessOutput) GetOutput() isProcessOutput_Output {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ProcessOutput) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Output.(*ProcessOutput_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ProcessOutput) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Output.(*ProcessOutput_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ProcessOutput) GetExit() *Process {
	if x != nil {
		if x, ok := x.Output.(*ProcessOutput_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

type isProcessOutput_Output interface {
	isProcessOutput_Output()
}

type ProcessOutput_Stdout struct {
	// A chunk of standard output.
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ProcessOutput_Stderr struct {
	// A chunk of standard error.
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type ProcessOutput_Exit struct {
	// Final message: the process has exited and all output has been delivered.
	// Absent if the stream ends while the process is still running (follow=false).
	Exit *Process `protobuf:"bytes,3,opt,name=exit,proto3,oneof"`
}

func (*ProcessOutput_Stdout) isProcessOutput_Output() {}

func (*ProcessOutput_Stderr) isProcessOutput_Output() {}

func (*ProcessOutput_Exit) isProcessOutput_Output() {}

// One chunk of standard input for a process.
type WriteProcessInputRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the target process. Required on the first message; ignored afterwards.
	ProcessId string `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	// Bytes to write to stdin. May be empty, e.g. to only close stdin.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// If true, stdin is closed (EOF) after data is written. No further input is accepted.
	Close         bool `protobuf:"varint,3,opt,name=close,proto3" json:"close,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteProcessInputRequest) Reset() {
	*x = WriteProcessInputRequest{}
	mi := &file_ateenv_v1alpha_guest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteProcessInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteProcessInputRequest) ProtoMessage() {}

func (x *WriteProcessInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha_guest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteProcessInputRequest.ProtoReflect.Descriptor instead.
func (*WriteProcessInputRequest) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha_guest_proto_rawDescGZIP(), []int{5}
}

func (x *WriteProcessInputRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *WriteProcessInputRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WriteProcessInputRequest) GetClose() bool {
	if x != nil {
		return x.Close
	}
	return false
}

// Response confirming the input write.
type WriteProcessInputResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of bytes written to stdin across all messages in the stream.
	BytesWritten  int64 `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteProcessInputResponse) Reset() {
	*x = WriteProcessInputResponse{}
	mi := &file_ateenv_v1alpha_guest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteProcessInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteProcessInputResponse) ProtoMessage() {}

func (x *WriteProcessInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha_guest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteProcessInputResponse.ProtoReflect.Descriptor instead.
func (*WriteProcessInputResponse) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha_guest_proto_rawDescGZIP(), []int{6}
}

func (x *WriteProcessInputResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

// Request to send a signal to a process.
type SignalProcessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the target process.
	ProcessId string `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	// Signal to deliver to the process group.
	Signal        Signal `protobuf:"varint,2,opt,name=signal,proto3,enum=ateenv.v1alpha.Signal" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalProcessRequest) Reset() {
	*x = SignalProcessRequest{}
	mi := &file_ateenv_v1alpha_guest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalProcessRequest) ProtoMessage() {}

func (x *SignalProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha_guest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalProcessRequest.ProtoReflect.Descriptor instead.
func (*SignalProcessRequest) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha_guest_proto_rawDescGZIP(), []int{7}
}

func (x *SignalProcessRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *SignalProcessRequest) GetSignal() Signal {
	if x != nil {
		return x.Signal
	}
	return Signal_SIGNAL_UNSPECIFIED
}

// Request to read a file from the container.
type ReadFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute or workspace-relative path of the file to read.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Optional POSIX file mode permission (e.g. 0644). When set and the file
	// does not exist, it is created empty with this mode (parent directories
	// included) and the stream ends without chunks. When zero, a missing file
	// is a NOT_FOUND error. Existing files are never modified.
	Mode          uint32 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_ateenv_v1alpha_guest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha_guest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha_guest_proto_rawDescGZIP(), []int{8}
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadFileRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// Streamed chunk of file data.
type ReadFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw binary or text chunk of the file.
	Chunk         []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_ateenv_v1alpha_guest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha_guest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha_guest_proto_rawDescGZIP(), []int{9}
}

func (x *ReadFileResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

// Streamed request chunk for writing data to a file. path, mode and
// seek_offset are read from the first message only and ignored on all
// subsequent messages; every message may carry a chunk.
type WriteFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute or workspace-relative path of the file to write. Required on the
	// first message.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Optional POSIX file mode permission (e.g. 0644 or 0755), applied when the
	// file is created.
	Mode uint32 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	// Byte offset at which writing starts. Zero, the default, truncates the
	// file and rewrites it from the beginning. A positive offset keeps existing
	// content, begins writing at the offset (extending the file with zero bytes
	// if it is shorter), and leaves bytes after the written range in place.
	SeekOffset int64 `protobuf:"varint,3,opt,name=seek_offset,json=seekOffset,proto3" json:"seek_offset,omitempty"`
	// Raw binary or text chunk to write to the file.
	Chunk         []byte `protobuf:"bytes,4,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_ateenv_v1alpha_guest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha_guest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha_guest_proto_rawDescGZIP(), []int{10}
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *WriteFileRequest) GetSeekOffset() int64 {
	if x != nil {
		return x.SeekOffset
	}
	return 0
}

func (x *WriteFileRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

// Response confirming the write operation.
type WriteFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of bytes written across all stream chunks.
	BytesWritten  int64 `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_ateenv_v1alpha_guest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha_guest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha_guest_proto_rawDescGZIP(), []int{11}
}

func (x *WriteFileResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

var File_ateenv_v1alpha_guest_proto protoreflect.FileDescriptor

const file_ateenv_v1alpha_guest_proto_rawDesc = "" +
	"\n" +
	"\x1aateenv/v1alpha/guest.proto\x12\x0eateenv.v1alpha\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9d\x02\n" +
	"\aProcess\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\x122\n" +
	"\x05state\x18\x04 \x01(\x0e2\x1c.ateenv.v1alpha.ProcessStateR\x05state\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\"\x84\x02\n" +
	"\x13StartProcessRequest\x12\x18\n" +
	"\acommand\x18\x01 \x03(\tR\acommand\x12\x10\n" +
	"\x03cwd\x18\x02 \x01(\tR\x03cwd\x12>\n" +
	"\x03env\x18\x03 \x03(\v2,.ateenv.v1alpha.StartProcessRequest.EnvEntryR\x03env\x12\x14\n" +
	"\x05stdin\x18\x04 \x01(\bR\x05stdin\x123\n" +
	"\atimeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"2\n" +
	"\x11GetProcessRequest\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\"\x9d\x01\n" +
	"\x1aStreamProcessOutputRequest\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12#\n" +
	"\rstdout_offset\x18\x02 \x01(\x03R\fstdoutOffset\x12#\n" +
	"\rstderr_offset\x18\x03 \x01(\x03R\fstderrOffset\x12\x16\n" +
	"\x06follow\x18\x04 \x01(\bR\x06follow\"|\n" +
	"\rProcessOutput\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x12-\n" +
	"\x04exit\x18\x03 \x01(\v2\x17.ateenv.v1alpha.ProcessH\x00R\x04exitB\b\n" +
	"\x06output\"c\n" +
	"\x18WriteProcessInputRequest\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x14\n" +
	"\x05close\x18\x03 \x01(\bR\x05close\"@\n" +
	"\x19WriteProcessInputResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x03R\fbytesWritten\"e\n" +
	"\x14SignalProcessRequest\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12.\n" +
	"\x06signal\x18\x02 \x01(\x0e2\x16.ateenv.v1alpha.SignalR\x06signal\"9\n" +
	"\x0fReadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\"(\n" +
	"\x10ReadFileResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"q\n" +
	"\x10WriteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x1f\n" +
	"\vseek_offset\x18\x03 \x01(\x03R\n" +
	"seekOffset\x12\x14\n" +
	"\x05chunk\x18\x04 \x01(\fR\x05chunk\"8\n" +
	"\x11WriteFileResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x03R\fbytesWritten*b\n" +
	"\fProcessState\x12\x1d\n" +
	"\x19PROCESS_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PROCESS_STATE_RUNNING\x10\x01\x12\x18\n" +
	"\x14PROCESS_STATE_EXITED\x10\x02*\x87\x04\n" +
	"\x06Signal\x12\x16\n" +
	"\x12SIGNAL_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"SIGNAL_HUP\x10\x01\x12\x0e\n" +
	"\n" +
	"SIGNAL_INT\x10\x02\x12\x0f\n" +
	"\vSIGNAL_QUIT\x10\x03\x12\x0e\n" +
	"\n" +
	"SIGNAL_ILL\x10\x04\x12\x0f\n" +
	"\vSIGNAL_TRAP\x10\x05\x12\x0f\n" +
	"\vSIGNAL_ABRT\x10\x06\x12\x0e\n" +
	"\n" +
	"SIGNAL_BUS\x10\a\x12\x0e\n" +
	"\n" +
	"SIGNAL_FPE\x10\b\x12\x0f\n" +
	"\vSIGNAL_KILL\x10\t\x12\x0f\n" +
	"\vSIGNAL_USR1\x10\n" +
	"\x12\x0f\n" +
	"\vSIGNAL_SEGV\x10\v\x12\x0f\n" +
	"\vSIGNAL_USR2\x10\f\x12\x0f\n" +
	"\vSIGNAL_PIPE\x10\r\x12\x0f\n" +
	"\vSIGNAL_ALRM\x10\x0e\x12\x0f\n" +
	"\vSIGNAL_TERM\x10\x0f\x12\x0f\n" +
	"\vSIGNAL_CHLD\x10\x11\x12\x0f\n" +
	"\vSIGNAL_CONT\x10\x12\x12\x0f\n" +
	"\vSIGNAL_STOP\x10\x13\x12\x0f\n" +
	"\vSIGNAL_TSTP\x10\x14\x12\x0f\n" +
	"\vSIGNAL_TTIN\x10\x15\x12\x0f\n" +
	"\vSIGNAL_TTOU\x10\x16\x12\x0e\n" +
	"\n" +
	"SIGNAL_URG\x10\x17\x12\x0f\n" +
	"\vSIGNAL_XCPU\x10\x18\x12\x0f\n" +
	"\vSIGNAL_XFSZ\x10\x19\x12\x11\n" +
	"\rSIGNAL_VTALRM\x10\x1a\x12\x0f\n" +
	"\vSIGNAL_PROF\x10\x1b\x12\x10\n" +
	"\fSIGNAL_WINCH\x10\x1c\x12\r\n" +
	"\tSIGNAL_IO\x10\x1d\x12\x0e\n" +
	"\n" +
	"SIGNAL_SYS\x10\x1f2\xc8\x03\n" +
	"\x0eProcessService\x12L\n" +
	"\fStartProcess\x12#.ateenv.v1alpha.StartProcessRequest\x1a\x17.ateenv.v1alpha.Process\x12H\n" +
	"\n" +
	"GetProcess\x12!.ateenv.v1alpha.GetProcessRequest\x1a\x17.ateenv.v1alpha.Process\x12b\n" +
	"\x13StreamProcessOutput\x12*.ateenv.v1alpha.StreamProcessOutputRequest\x1a\x1d.ateenv.v1alpha.ProcessOutput0\x01\x12j\n" +
	"\x11WriteProcessInput\x12(.ateenv.v1alpha.WriteProcessInputRequest\x1a).ateenv.v1alpha.WriteProcessInputResponse(\x01\x12N\n" +
	"\rSignalProcess\x12$.ateenv.v1alpha.SignalProcessRequest\x1a\x17.ateenv.v1alpha.Process2\xb8\x01\n" +
	"\x11FileSystemService\x12O\n" +
	"\bReadFile\x12\x1f.ateenv.v1alpha.ReadFileRequest\x1a .ateenv.v1alpha.ReadFileResponse0\x01\x12R\n" +
	"\tWriteFile\x12 .ateenv.v1alpha.WriteFileRequest\x1a!.ateenv.v1alpha.WriteFileResponse(\x01BCZAgithub.com/agent-substrate/env/proto/ateenv/v1alpha;ateenvv1alphab\x06proto3"

var (
	file_ateenv_v1alpha_guest_proto_rawDescOnce sync.Once
	file_ateenv_v1alpha_guest_proto_rawDescData []byte
)

func file_ateenv_v1alpha_guest_proto_rawDescGZIP() []byte {
	file_ateenv_v1alpha_guest_proto_rawDescOnce.Do(func() {
		file_ateenv_v1alpha_guest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ateenv_v1alpha_guest_proto_rawDesc), len(file_ateenv_v1alpha_guest_proto_rawDesc)))
	})
	return file_ateenv_v1alpha_guest_proto_rawDescData
}

var file_ateenv_v1alpha_guest_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ateenv_v1alpha_guest_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_ateenv_v1alpha_guest_proto_goTypes = []any{
	(ProcessState)(0),                  // 0: ateenv.v1alpha.ProcessState
	(Signal)(0),                        // 1: ateenv.v1alpha.Signal
	(*Process)(nil),                    // 2: ateenv.v1alpha.Process
	(*StartProcessRequest)(nil),        // 3: ateenv.v1alpha.StartProcessRequest
	(*GetProcessRequest)(nil),          // 4: ateenv.v1alpha.GetProcessRequest
	(*StreamProcessOutputRequest)(nil), // 5: ateenv.v1alpha.StreamProcessOutputRequest
	(*ProcessOutput)(nil),              // 6: ateenv.v1alpha.ProcessOutput
	(*WriteProcessInputRequest)(nil),   // 7: ateenv.v1alpha.WriteProcessInputRequest
	(*WriteProcessInputResponse)(nil),  // 8: ateenv.v1alpha.WriteProcessInputResponse
	(*SignalProcessRequest)(nil),       // 9: ateenv.v1alpha.SignalProcessRequest
	(*ReadFileRequest)(nil),            // 10: ateenv.v1alpha.ReadFileRequest
	(*ReadFileResponse)(nil),           // 11: ateenv.v1alpha.ReadFileResponse
	(*WriteFileRequest)(nil),           // 12: ateenv.v1alpha.WriteFileRequest
	(*WriteFileResponse)(nil),          // 13: ateenv.v1alpha.WriteFileResponse
	nil,                                // 14: ateenv.v1alpha.StartProcessRequest.EnvEntry
	(*timestamppb.Timestamp)(nil),      // 15: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),        // 16: google.protobuf.Duration
}
var file_ateenv_v1alpha_guest_proto_depIdxs = []int32{
	0,  // 0: ateenv.v1alpha.Process.state:type_name -> ateenv.v1alpha.ProcessState
	15, // 1: ateenv.v1alpha.Process.started_at:type_name -> google.protobuf.Timestamp
	15, // 2: ateenv.v1alpha.Process.finished_at:type_name -> google.protobuf.Timestamp
	14, // 3: ateenv.v1alpha.StartProcessRequest.env:type_name -> ateenv.v1alpha.StartProcessRequest.EnvEntry
	16, // 4: ateenv.v1alpha.StartProcessRequest.timeout:type_name -> google.protobuf.Duration
	2,  // 5: ateenv.v1alpha.ProcessOutput.exit:type_name -> ateenv.v1alpha.Process
	1,  // 6: ateenv.v1alpha.SignalProcessRequest.signal:type_name -> ateenv.v1alpha.Signal
	3,  // 7: ateenv.v1alpha.ProcessService.StartProcess:input_type -> ateenv.v1alpha.StartProcessRequest
	4,  // 8: ateenv.v1alpha.ProcessService.GetProcess:input_type -> ateenv.v1alpha.GetProcessRequest
	5,  // 9: ateenv.v1alpha.ProcessService.StreamProcessOutput:input_type -> ateenv.v1alpha.StreamProcessOutputRequest
	7,  // 10: ateenv.v1alpha.ProcessService.WriteProcessInput:input_type -> ateenv.v1alpha.WriteProcessInputRequest
	9,  // 11: ateenv.v1alpha.ProcessService.SignalProcess:input_type -> ateenv.v1alpha.SignalProcessRequest
	10, // 12: ateenv.v1alpha.FileSystemService.ReadFile:input_type -> ateenv.v1alpha.ReadFileRequest
	12, // 13: ateenv.v1alpha.FileSystemService.WriteFile:input_type -> ateenv.v1alpha.WriteFileRequest
	2,  // 14: ateenv.v1alpha.ProcessService.StartProcess:output_type -> ateenv.v1alpha.Process
	2,  // 15: ateenv.v1alpha.ProcessService.GetProcess:output_type -> ateenv.v1alpha.Process
	6,  // 16: ateenv.v1alpha.ProcessService.StreamProcessOutput:output_type -> ateenv.v1alpha.ProcessOutput
	8,  // 17: ateenv.v1alpha.ProcessService.WriteProcessInput:output_type -> ateenv.v1alpha.WriteProcessInputResponse
	2,  // 18: ateenv.v1alpha.ProcessService.SignalProcess:output_type -> ateenv.v1alpha.Process
	11, // 19: ateenv.v1alpha.FileSystemService.ReadFile:output_type -> ateenv.v1alpha.ReadFileResponse
	13, // 20: ateenv.v1alpha.FileSystemService.WriteFile:output_type -> ateenv.v1alpha.WriteFileResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_ateenv_v1alpha_guest_proto_init() }
func file_ateenv_v1alpha_guest_proto_init() {
	if File_ateenv_v1alpha_guest_proto != nil {
		return
	}
	file_ateenv_v1alpha_guest_proto_msgTypes[4].OneofWrappers = []any{
		(*ProcessOutput_Stdout)(nil),
		(*ProcessOutput_Stderr)(nil),
		(*ProcessOutput_Exit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ateenv_v1alpha_guest_proto_rawDesc), len(file_ateenv_v1alpha_guest_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_ateenv_v1alpha_guest_proto_goTypes,
		DependencyIndexes: file_ateenv_v1alpha_guest_proto_depIdxs,
		EnumInfos:         file_ateenv_v1alpha_guest_proto_enumTypes,
		MessageInfos:      file_ateenv_v1alpha_guest_proto_msgTypes,
	}.Build()
	File_ateenv_v1alpha_guest_proto = out.File
	file_ateenv_v1alpha_guest_proto_goTypes = nil
	file_ateenv_v1alpha_guest_proto_depIdxs = nil
}
