import time
import pytest
from ate_env.adapters.swebench import SWEBENCH_SAMPLE_TASK, SweBenchAdapter
from ate_env.config import FleetConfig
from ate_env.fleet import SandboxFleet


def test_poc_swebench_rollout():
    """
    End-to-End PoC Rollout:
    Simulates an RL post-training step with candidate patches evaluated
    against the curated SWE-bench task using the Unified Sandbox SDK.
    """
    task = SweBenchAdapter.to_task(SWEBENCH_SAMPLE_TASK)

    cfg = FleetConfig(
        backend="mock",
        strategy="pipelined",
        batch_size=2,
        max_warmpool_replicas=2,
    )
    fleet = SandboxFleet(cfg)
    fleet.load_tasks([task])
    fleet.setup()

    # Rollout candidate patches generated by Sampler / vLLM
    candidate_passing_patch = (
        "--- a/testing/test_helpconfig.py\n"
        "+++ b/testing/test_helpconfig.py\n"
        "@@ -1,3 +1,4 @@\n"
        "+# Patch that fixes fixture display\n"
    )
    candidate_failing_patch = (
        "--- a/testing/test_helpconfig.py\n"
        "+++ b/testing/test_helpconfig.py\n"
        "@@ -1,3 +1,4 @@\n"
        "+raise RuntimeError('Syntax error in test')\n"
    )

    # 1. Evaluate Passing Candidate
    t0 = time.monotonic()
    handle = fleet.acquire(task)
    ttfe = time.monotonic() - t0
    assert ttfe < 1.0  # Instant claim from warm pool

    eval_result_pass = SweBenchAdapter.evaluate(
        handle=handle,
        patch_content=candidate_passing_patch,
        test_cmd=SWEBENCH_SAMPLE_TASK["test_cmd"]
    )
    fleet.release(handle)

    assert eval_result_pass["passed"] is True
    assert eval_result_pass["reward"] == 1.0
    assert "1 passed" in eval_result_pass["logs"]

    # 2. Evaluate Failing Candidate
    handle2 = fleet.acquire(task)
    # Set failing test response on mock runtime
    handle2.runtime.set_response(
        "pytest testing/test_helpconfig.py",
        handle2.runtime.exec("echo 'pytest: FAIL'; exit 1")
    )
    # Temporarily set failing exit code
    from ate_env.types import ExecResult
    handle2.runtime.set_response(
        "pytest testing/test_helpconfig.py",
        ExecResult(exit_code=1, stdout="=== FAILURES ===\n", stderr="AssertionError")
    )

    eval_result_fail = SweBenchAdapter.evaluate(
        handle=handle2,
        patch_content=candidate_failing_patch,
        test_cmd=SWEBENCH_SAMPLE_TASK["test_cmd"]
    )
    fleet.release(handle2)

    assert eval_result_fail["passed"] is False
    assert eval_result_fail["reward"] == 0.0

    # 3. Teardown
    fleet.teardown()
