# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import env_pb2 as ateenv_dot_v1alpha_dot_env__pb2


class EnvironmentServiceStub(object):
    """TODO(jbd): Migrate data plane (shell/fs) to guest.proto (ProcessService/FileSystemService).
    TODO(jbd): Remove env legacy HTTP REST endpoints for environment lifecycle.
    TODO(jbd): Update remaining examples and documentation.
    TODO(jbd): Add ListEnvironments to EnvironmentService.

    ============================================================================
    --- SERVICES ---
    ============================================================================

    EnvironmentService manages the lifecycle of isolated execution environments.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateEnvironment = channel.unary_unary(
                '/ateenv.v1alpha.EnvironmentService/CreateEnvironment',
                request_serializer=ateenv_dot_v1alpha_dot_env__pb2.CreateEnvironmentRequest.SerializeToString,
                response_deserializer=ateenv_dot_v1alpha_dot_env__pb2.CreateEnvironmentResponse.FromString,
                )
        self.GetEnvironment = channel.unary_unary(
                '/ateenv.v1alpha.EnvironmentService/GetEnvironment',
                request_serializer=ateenv_dot_v1alpha_dot_env__pb2.GetEnvironmentRequest.SerializeToString,
                response_deserializer=ateenv_dot_v1alpha_dot_env__pb2.GetEnvironmentResponse.FromString,
                )
        self.SuspendEnvironment = channel.unary_unary(
                '/ateenv.v1alpha.EnvironmentService/SuspendEnvironment',
                request_serializer=ateenv_dot_v1alpha_dot_env__pb2.SuspendEnvironmentRequest.SerializeToString,
                response_deserializer=ateenv_dot_v1alpha_dot_env__pb2.SuspendEnvironmentResponse.FromString,
                )
        self.DeleteEnvironment = channel.unary_unary(
                '/ateenv.v1alpha.EnvironmentService/DeleteEnvironment',
                request_serializer=ateenv_dot_v1alpha_dot_env__pb2.DeleteEnvironmentRequest.SerializeToString,
                response_deserializer=ateenv_dot_v1alpha_dot_env__pb2.DeleteEnvironmentResponse.FromString,
                )


class EnvironmentServiceServicer(object):
    """TODO(jbd): Migrate data plane (shell/fs) to guest.proto (ProcessService/FileSystemService).
    TODO(jbd): Remove env legacy HTTP REST endpoints for environment lifecycle.
    TODO(jbd): Update remaining examples and documentation.
    TODO(jbd): Add ListEnvironments to EnvironmentService.

    ============================================================================
    --- SERVICES ---
    ============================================================================

    EnvironmentService manages the lifecycle of isolated execution environments.
    """

    def CreateEnvironment(self, request, context):
        """CreateEnvironment registers and starts a new environment from an actor template.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnvironment(self, request, context):
        """GetEnvironment retrieves the status and configuration of an existing environment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuspendEnvironment(self, request, context):
        """SuspendEnvironment checkpoints and stops an active environment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEnvironment(self, request, context):
        """DeleteEnvironment permanently removes an environment and its associated resources.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnvironmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEnvironment,
                    request_deserializer=ateenv_dot_v1alpha_dot_env__pb2.CreateEnvironmentRequest.FromString,
                    response_serializer=ateenv_dot_v1alpha_dot_env__pb2.CreateEnvironmentResponse.SerializeToString,
            ),
            'GetEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnvironment,
                    request_deserializer=ateenv_dot_v1alpha_dot_env__pb2.GetEnvironmentRequest.FromString,
                    response_serializer=ateenv_dot_v1alpha_dot_env__pb2.GetEnvironmentResponse.SerializeToString,
            ),
            'SuspendEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.SuspendEnvironment,
                    request_deserializer=ateenv_dot_v1alpha_dot_env__pb2.SuspendEnvironmentRequest.FromString,
                    response_serializer=ateenv_dot_v1alpha_dot_env__pb2.SuspendEnvironmentResponse.SerializeToString,
            ),
            'DeleteEnvironment': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEnvironment,
                    request_deserializer=ateenv_dot_v1alpha_dot_env__pb2.DeleteEnvironmentRequest.FromString,
                    response_serializer=ateenv_dot_v1alpha_dot_env__pb2.DeleteEnvironmentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ateenv.v1alpha.EnvironmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EnvironmentService(object):
    """TODO(jbd): Migrate data plane (shell/fs) to guest.proto (ProcessService/FileSystemService).
    TODO(jbd): Remove env legacy HTTP REST endpoints for environment lifecycle.
    TODO(jbd): Update remaining examples and documentation.
    TODO(jbd): Add ListEnvironments to EnvironmentService.

    ============================================================================
    --- SERVICES ---
    ============================================================================

    EnvironmentService manages the lifecycle of isolated execution environments.
    """

    @staticmethod
    def CreateEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ateenv.v1alpha.EnvironmentService/CreateEnvironment',
            ateenv_dot_v1alpha_dot_env__pb2.CreateEnvironmentRequest.SerializeToString,
            ateenv_dot_v1alpha_dot_env__pb2.CreateEnvironmentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ateenv.v1alpha.EnvironmentService/GetEnvironment',
            ateenv_dot_v1alpha_dot_env__pb2.GetEnvironmentRequest.SerializeToString,
            ateenv_dot_v1alpha_dot_env__pb2.GetEnvironmentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SuspendEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ateenv.v1alpha.EnvironmentService/SuspendEnvironment',
            ateenv_dot_v1alpha_dot_env__pb2.SuspendEnvironmentRequest.SerializeToString,
            ateenv_dot_v1alpha_dot_env__pb2.SuspendEnvironmentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteEnvironment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ateenv.v1alpha.EnvironmentService/DeleteEnvironment',
            ateenv_dot_v1alpha_dot_env__pb2.DeleteEnvironmentRequest.SerializeToString,
            ateenv_dot_v1alpha_dot_env__pb2.DeleteEnvironmentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
