# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import guest_pb2 as ateenv_dot_v1alpha_dot_guest__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ateenv/v1alpha/guest_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProcessServiceStub:
    """============================================================================
    --- SERVICES ---
    ============================================================================

    ProcessService manages the lifecycle and I/O of processes running inside
    the container.

    A process is started asynchronously and addressed by its process_id. Output
    is spooled by the guest and can be streamed live or replayed from an offset.
    Input is fed through a client stream, and any POSIX signal can be delivered
    to the process group.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartProcess = channel.unary_unary(
                '/ateenv.v1alpha.ProcessService/StartProcess',
                request_serializer=ateenv_dot_v1alpha_dot_guest__pb2.StartProcessRequest.SerializeToString,
                response_deserializer=ateenv_dot_v1alpha_dot_guest__pb2.Process.FromString,
                _registered_method=True)
        self.GetProcess = channel.unary_unary(
                '/ateenv.v1alpha.ProcessService/GetProcess',
                request_serializer=ateenv_dot_v1alpha_dot_guest__pb2.GetProcessRequest.SerializeToString,
                response_deserializer=ateenv_dot_v1alpha_dot_guest__pb2.Process.FromString,
                _registered_method=True)
        self.StreamProcessOutput = channel.unary_stream(
                '/ateenv.v1alpha.ProcessService/StreamProcessOutput',
                request_serializer=ateenv_dot_v1alpha_dot_guest__pb2.StreamProcessOutputRequest.SerializeToString,
                response_deserializer=ateenv_dot_v1alpha_dot_guest__pb2.ProcessOutput.FromString,
                _registered_method=True)
        self.WriteProcessInput = channel.stream_unary(
                '/ateenv.v1alpha.ProcessService/WriteProcessInput',
                request_serializer=ateenv_dot_v1alpha_dot_guest__pb2.WriteProcessInputRequest.SerializeToString,
                response_deserializer=ateenv_dot_v1alpha_dot_guest__pb2.WriteProcessInputResponse.FromString,
                _registered_method=True)
        self.SignalProcess = channel.unary_unary(
                '/ateenv.v1alpha.ProcessService/SignalProcess',
                request_serializer=ateenv_dot_v1alpha_dot_guest__pb2.SignalProcessRequest.SerializeToString,
                response_deserializer=ateenv_dot_v1alpha_dot_guest__pb2.Process.FromString,
                _registered_method=True)


class ProcessServiceServicer:
    """============================================================================
    --- SERVICES ---
    ============================================================================

    ProcessService manages the lifecycle and I/O of processes running inside
    the container.

    A process is started asynchronously and addressed by its process_id. Output
    is spooled by the guest and can be streamed live or replayed from an offset.
    Input is fed through a client stream, and any POSIX signal can be delivered
    to the process group.
    """

    def StartProcess(self, request, context):
        """StartProcess launches a process in the background and returns its
        Process resource immediately.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcess(self, request, context):
        """GetProcess returns the current state of a process.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamProcessOutput(self, request, context):
        """StreamProcessOutput streams stdout and stderr from a process. Once the
        process has exited and all output has been delivered, the stream ends
        with a final exit message carrying the finished Process. Following with
        no interest in output (offsets past the end of the spool) is the way to
        wait for a process to exit.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteProcessInput(self, request_iterator, context):
        """WriteProcessInput feeds bytes to the stdin of a process started with
        stdin enabled. Multiple calls may be made over the life of a process;
        stdin stays open until a message sets close, or the process exits.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignalProcess(self, request, context):
        """SignalProcess delivers a signal to the process and its process group and
        returns the process state right after delivery. Use StreamProcessOutput
        to observe the effect.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProcessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.StartProcess,
                    request_deserializer=ateenv_dot_v1alpha_dot_guest__pb2.StartProcessRequest.FromString,
                    response_serializer=ateenv_dot_v1alpha_dot_guest__pb2.Process.SerializeToString,
            ),
            'GetProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcess,
                    request_deserializer=ateenv_dot_v1alpha_dot_guest__pb2.GetProcessRequest.FromString,
                    response_serializer=ateenv_dot_v1alpha_dot_guest__pb2.Process.SerializeToString,
            ),
            'StreamProcessOutput': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamProcessOutput,
                    request_deserializer=ateenv_dot_v1alpha_dot_guest__pb2.StreamProcessOutputRequest.FromString,
                    response_serializer=ateenv_dot_v1alpha_dot_guest__pb2.ProcessOutput.SerializeToString,
            ),
            'WriteProcessInput': grpc.stream_unary_rpc_method_handler(
                    servicer.WriteProcessInput,
                    request_deserializer=ateenv_dot_v1alpha_dot_guest__pb2.WriteProcessInputRequest.FromString,
                    response_serializer=ateenv_dot_v1alpha_dot_guest__pb2.WriteProcessInputResponse.SerializeToString,
            ),
            'SignalProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.SignalProcess,
                    request_deserializer=ateenv_dot_v1alpha_dot_guest__pb2.SignalProcessRequest.FromString,
                    response_serializer=ateenv_dot_v1alpha_dot_guest__pb2.Process.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ateenv.v1alpha.ProcessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ateenv.v1alpha.ProcessService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProcessService:
    """============================================================================
    --- SERVICES ---
    ============================================================================

    ProcessService manages the lifecycle and I/O of processes running inside
    the container.

    A process is started asynchronously and addressed by its process_id. Output
    is spooled by the guest and can be streamed live or replayed from an offset.
    Input is fed through a client stream, and any POSIX signal can be delivered
    to the process group.
    """

    @staticmethod
    def StartProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ateenv.v1alpha.ProcessService/StartProcess',
            ateenv_dot_v1alpha_dot_guest__pb2.StartProcessRequest.SerializeToString,
            ateenv_dot_v1alpha_dot_guest__pb2.Process.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ateenv.v1alpha.ProcessService/GetProcess',
            ateenv_dot_v1alpha_dot_guest__pb2.GetProcessRequest.SerializeToString,
            ateenv_dot_v1alpha_dot_guest__pb2.Process.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamProcessOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ateenv.v1alpha.ProcessService/StreamProcessOutput',
            ateenv_dot_v1alpha_dot_guest__pb2.StreamProcessOutputRequest.SerializeToString,
            ateenv_dot_v1alpha_dot_guest__pb2.ProcessOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteProcessInput(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ateenv.v1alpha.ProcessService/WriteProcessInput',
            ateenv_dot_v1alpha_dot_guest__pb2.WriteProcessInputRequest.SerializeToString,
            ateenv_dot_v1alpha_dot_guest__pb2.WriteProcessInputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignalProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ateenv.v1alpha.ProcessService/SignalProcess',
            ateenv_dot_v1alpha_dot_guest__pb2.SignalProcessRequest.SerializeToString,
            ateenv_dot_v1alpha_dot_guest__pb2.Process.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FileSystemServiceStub:
    """FileSystemService provides streaming file reading and writing capabilities inside
    the container rootfs/workspace to prevent memory exhaustion (OOM).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadFile = channel.unary_stream(
                '/ateenv.v1alpha.FileSystemService/ReadFile',
                request_serializer=ateenv_dot_v1alpha_dot_guest__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=ateenv_dot_v1alpha_dot_guest__pb2.ReadFileResponse.FromString,
                _registered_method=True)
        self.WriteFile = channel.stream_unary(
                '/ateenv.v1alpha.FileSystemService/WriteFile',
                request_serializer=ateenv_dot_v1alpha_dot_guest__pb2.WriteFileRequest.SerializeToString,
                response_deserializer=ateenv_dot_v1alpha_dot_guest__pb2.WriteFileResponse.FromString,
                _registered_method=True)


class FileSystemServiceServicer:
    """FileSystemService provides streaming file reading and writing capabilities inside
    the container rootfs/workspace to prevent memory exhaustion (OOM).
    """

    def ReadFile(self, request, context):
        """ReadFile streams the binary or text contents of a file in chunks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request_iterator, context):
        """WriteFile streams binary or text chunks directly to a target file.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileSystemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=ateenv_dot_v1alpha_dot_guest__pb2.ReadFileRequest.FromString,
                    response_serializer=ateenv_dot_v1alpha_dot_guest__pb2.ReadFileResponse.SerializeToString,
            ),
            'WriteFile': grpc.stream_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=ateenv_dot_v1alpha_dot_guest__pb2.WriteFileRequest.FromString,
                    response_serializer=ateenv_dot_v1alpha_dot_guest__pb2.WriteFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ateenv.v1alpha.FileSystemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ateenv.v1alpha.FileSystemService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileSystemService:
    """FileSystemService provides streaming file reading and writing capabilities inside
    the container rootfs/workspace to prevent memory exhaustion (OOM).
    """

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ateenv.v1alpha.FileSystemService/ReadFile',
            ateenv_dot_v1alpha_dot_guest__pb2.ReadFileRequest.SerializeToString,
            ateenv_dot_v1alpha_dot_guest__pb2.ReadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ateenv.v1alpha.FileSystemService/WriteFile',
            ateenv_dot_v1alpha_dot_guest__pb2.WriteFileRequest.SerializeToString,
            ateenv_dot_v1alpha_dot_guest__pb2.WriteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
