// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package guest

import (
	"context"
	"strconv"
	"sync"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
)

// Ownership metadata is issued by a trusted, authenticated controller. This
// fences stale callers; it is not an authentication mechanism. Generations
// must increase across restores, rather than being generated by the guest.
const OwnerGenerationHeader = "ate-owner-generation"
const OwnerTokenHeader = "ate-owner-token"

type ownerEpoch struct {
	ctx    context.Context
	cancel context.CancelFunc
	calls  sync.WaitGroup
}

type ownerFence struct {
	mu         sync.Mutex
	generation int64
	token      string
	epoch      *ownerEpoch
	drain      func() error
}

func (f *ownerFence) acquire(ctx context.Context) (context.Context, func(), error) {
	md, _ := metadata.FromIncomingContext(ctx)
	generations, tokens := md.Get(OwnerGenerationHeader), md.Get(OwnerTokenHeader)
	if len(generations) != 1 || len(tokens) != 1 || tokens[0] == "" || len(tokens[0]) > 256 {
		return nil, nil, status.Error(codes.FailedPrecondition, "guest ownership metadata required")
	}
	generation, err := strconv.ParseInt(generations[0], 10, 64)
	if err != nil || generation < 1 {
		return nil, nil, status.Error(codes.InvalidArgument, "invalid owner generation")
	}
	f.mu.Lock()
	defer f.mu.Unlock()
	if generation < f.generation || generation == f.generation && tokens[0] != f.token {
		return nil, nil, status.Error(codes.FailedPrecondition, "stale guest owner")
	}
	if generation == f.generation && f.epoch != nil && f.epoch.ctx.Err() != nil {
		return nil, nil, status.Error(codes.FailedPrecondition, "guest owner is closed")
	}
	if generation > f.generation {
		if f.epoch != nil {
			f.epoch.cancel()
			f.epoch.calls.Wait()
		}
		// No calls from the preceding epoch can spawn while the drain runs.
		if err := f.drain(); err != nil {
			return nil, nil, err
		}
		epochCtx, cancel := context.WithCancel(context.Background())
		f.epoch = &ownerEpoch{ctx: epochCtx, cancel: cancel}
		f.generation, f.token = generation, tokens[0]
	}
	epoch := f.epoch
	epoch.calls.Add(1)
	callCtx, cancel := context.WithCancel(ctx)
	stop := context.AfterFunc(epoch.ctx, cancel)
	return callCtx, func() { stop(); cancel(); epoch.calls.Done() }, nil
}

func (f *ownerFence) unary(ctx context.Context, req any, _ *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (any, error) {
	ctx, release, err := f.acquire(ctx)
	if err != nil {
		return nil, err
	}
	defer release()
	return handler(ctx, req)
}

func (f *ownerFence) stream(srv any, stream grpc.ServerStream, _ *grpc.StreamServerInfo, handler grpc.StreamHandler) error {
	ctx, release, err := f.acquire(stream.Context())
	if err != nil {
		return err
	}
	defer release()
	return handler(srv, &ownedStream{ServerStream: stream, ctx: ctx})
}

type ownedStream struct {
	grpc.ServerStream
	ctx context.Context
}

func (s *ownedStream) Context() context.Context { return s.ctx }

// Returning from the handler closes the underlying transport, releasing an
// in-flight Send/Recv even when the old caller stopped consuming the stream.
func (s *ownedStream) operation(call func() error) error {
	if err := s.ctx.Err(); err != nil {
		return status.FromContextError(err).Err()
	}
	result := make(chan error, 1)
	go func() { result <- call() }()
	select {
	case err := <-result:
		return err
	case <-s.ctx.Done():
		return status.FromContextError(s.ctx.Err()).Err()
	}
}
func (s *ownedStream) SendMsg(m any) error {
	return s.operation(func() error { return s.ServerStream.SendMsg(m) })
}
func (s *ownedStream) RecvMsg(m any) error {
	return s.operation(func() error { return s.ServerStream.RecvMsg(m) })
}
