# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import guest_pb2 as ateenv_dot_v1_dot_guest__pb2


class ProcessServiceStub(object):
    """============================================================================
    --- SERVICES ---
    ============================================================================

    ProcessService manages the asynchronous lifecycle and output streaming of
    processes running inside the container.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartProcess = channel.unary_unary(
                '/ateenv.v1.ProcessService/StartProcess',
                request_serializer=ateenv_dot_v1_dot_guest__pb2.StartProcessRequest.SerializeToString,
                response_deserializer=ateenv_dot_v1_dot_guest__pb2.StartProcessResponse.FromString,
                )
        self.GetProcess = channel.unary_unary(
                '/ateenv.v1.ProcessService/GetProcess',
                request_serializer=ateenv_dot_v1_dot_guest__pb2.GetProcessRequest.SerializeToString,
                response_deserializer=ateenv_dot_v1_dot_guest__pb2.Process.FromString,
                )
        self.StreamProcessOutputs = channel.unary_stream(
                '/ateenv.v1.ProcessService/StreamProcessOutputs',
                request_serializer=ateenv_dot_v1_dot_guest__pb2.StreamProcessOutputsRequest.SerializeToString,
                response_deserializer=ateenv_dot_v1_dot_guest__pb2.OutputChunk.FromString,
                )
        self.KillProcess = channel.unary_unary(
                '/ateenv.v1.ProcessService/KillProcess',
                request_serializer=ateenv_dot_v1_dot_guest__pb2.KillProcessRequest.SerializeToString,
                response_deserializer=ateenv_dot_v1_dot_guest__pb2.KillProcessResponse.FromString,
                )


class ProcessServiceServicer(object):
    """============================================================================
    --- SERVICES ---
    ============================================================================

    ProcessService manages the asynchronous lifecycle and output streaming of
    processes running inside the container.
    """

    def StartProcess(self, request, context):
        """StartProcess launches a long-running process asynchronously in the background
        and immediately returns a unique process_id for tracking.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcess(self, request, context):
        """GetProcess retrieves the current metadata, lifecycle state, and timestamps of a process.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamProcessOutputs(self, request, context):
        """StreamProcessOutputs streams real-time stdout and stderr from a process.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KillProcess(self, request, context):
        """KillProcess terminates a running asynchronous process and its child process tree.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProcessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.StartProcess,
                    request_deserializer=ateenv_dot_v1_dot_guest__pb2.StartProcessRequest.FromString,
                    response_serializer=ateenv_dot_v1_dot_guest__pb2.StartProcessResponse.SerializeToString,
            ),
            'GetProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcess,
                    request_deserializer=ateenv_dot_v1_dot_guest__pb2.GetProcessRequest.FromString,
                    response_serializer=ateenv_dot_v1_dot_guest__pb2.Process.SerializeToString,
            ),
            'StreamProcessOutputs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamProcessOutputs,
                    request_deserializer=ateenv_dot_v1_dot_guest__pb2.StreamProcessOutputsRequest.FromString,
                    response_serializer=ateenv_dot_v1_dot_guest__pb2.OutputChunk.SerializeToString,
            ),
            'KillProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.KillProcess,
                    request_deserializer=ateenv_dot_v1_dot_guest__pb2.KillProcessRequest.FromString,
                    response_serializer=ateenv_dot_v1_dot_guest__pb2.KillProcessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ateenv.v1.ProcessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProcessService(object):
    """============================================================================
    --- SERVICES ---
    ============================================================================

    ProcessService manages the asynchronous lifecycle and output streaming of
    processes running inside the container.
    """

    @staticmethod
    def StartProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ateenv.v1.ProcessService/StartProcess',
            ateenv_dot_v1_dot_guest__pb2.StartProcessRequest.SerializeToString,
            ateenv_dot_v1_dot_guest__pb2.StartProcessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ateenv.v1.ProcessService/GetProcess',
            ateenv_dot_v1_dot_guest__pb2.GetProcessRequest.SerializeToString,
            ateenv_dot_v1_dot_guest__pb2.Process.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamProcessOutputs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ateenv.v1.ProcessService/StreamProcessOutputs',
            ateenv_dot_v1_dot_guest__pb2.StreamProcessOutputsRequest.SerializeToString,
            ateenv_dot_v1_dot_guest__pb2.OutputChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def KillProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ateenv.v1.ProcessService/KillProcess',
            ateenv_dot_v1_dot_guest__pb2.KillProcessRequest.SerializeToString,
            ateenv_dot_v1_dot_guest__pb2.KillProcessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class FileSystemServiceStub(object):
    """FileSystemService provides streaming file reading and writing capabilities inside
    the container rootfs/workspace to prevent memory exhaustion (OOM).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadFile = channel.unary_stream(
                '/ateenv.v1.FileSystemService/ReadFile',
                request_serializer=ateenv_dot_v1_dot_guest__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=ateenv_dot_v1_dot_guest__pb2.FileChunk.FromString,
                )
        self.WriteFile = channel.stream_unary(
                '/ateenv.v1.FileSystemService/WriteFile',
                request_serializer=ateenv_dot_v1_dot_guest__pb2.WriteFileRequest.SerializeToString,
                response_deserializer=ateenv_dot_v1_dot_guest__pb2.WriteFileResponse.FromString,
                )


class FileSystemServiceServicer(object):
    """FileSystemService provides streaming file reading and writing capabilities inside
    the container rootfs/workspace to prevent memory exhaustion (OOM).
    """

    def ReadFile(self, request, context):
        """ReadFile streams the binary or text contents of a file in chunks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request_iterator, context):
        """WriteFile streams binary or text chunks directly to a target file.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileSystemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=ateenv_dot_v1_dot_guest__pb2.ReadFileRequest.FromString,
                    response_serializer=ateenv_dot_v1_dot_guest__pb2.FileChunk.SerializeToString,
            ),
            'WriteFile': grpc.stream_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=ateenv_dot_v1_dot_guest__pb2.WriteFileRequest.FromString,
                    response_serializer=ateenv_dot_v1_dot_guest__pb2.WriteFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ateenv.v1.FileSystemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileSystemService(object):
    """FileSystemService provides streaming file reading and writing capabilities inside
    the container rootfs/workspace to prevent memory exhaustion (OOM).
    """

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ateenv.v1.FileSystemService/ReadFile',
            ateenv_dot_v1_dot_guest__pb2.ReadFileRequest.SerializeToString,
            ateenv_dot_v1_dot_guest__pb2.FileChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/ateenv.v1.FileSystemService/WriteFile',
            ateenv_dot_v1_dot_guest__pb2.WriteFileRequest.SerializeToString,
            ateenv_dot_v1_dot_guest__pb2.WriteFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
