// Copyright 2026 The Agent Substrate Authors.

// The ateenv.v1alpha1 guest data plane: the gRPC contract between
// ate-env-api and the ate-env-guest daemon inside an environment.
//
// The contract treats connections as disposable. Every Process call is
// short-lived and unary; the durable handles are process ids and byte
// offsets, never a connection. A client that loses its connection —
// or whose environment is suspended and later resumed — polls again
// with the same handles and continues where it left off.
//
// Process outcomes are in-band (ExecResponse.error, ProcessInfo.exited);
// a non-OK gRPC status always means a transport or request fault. Reads
// (Get, List, ReadFile, Stat, ListDir) and WriteFile are safe to repeat
// verbatim. Start, Exec, WriteStdin, and Signal take effect at least
// once: a call that failed in transport may still have acted, so
// clients reconcile before resending — List shows whether a Start
// landed.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.27.0
// source: ateenv/v1alpha1/guest.proto

package ateenvv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecRequest describes a bounded command.
type ExecRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// command is the shell command line to run. Required.
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// cwd is the working directory. Defaults to the guest's working
	// directory. Relative paths resolve against it.
	Cwd string `protobuf:"bytes,2,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// env holds environment variables set on top of the guest's own.
	Env map[string]string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// stdin is fed to the command's standard input, which is then closed.
	Stdin []byte `protobuf:"bytes,4,opt,name=stdin,proto3" json:"stdin,omitempty"`
	// timeout_ms bounds the command's runtime; on expiry the process group
	// is killed and the response reports the timeout in error. 0 means no
	// timeout beyond the request deadline.
	TimeoutMs     int64 `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{0}
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ExecRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecRequest) GetStdin() []byte {
	if x != nil {
		return x.Stdin
	}
	return nil
}

func (x *ExecRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// ExecResponse is the outcome of an ExecRequest. It is returned with OK
// status whenever the request itself was valid; how the command fared is
// reported in-band.
type ExecResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stdout and stderr hold the captured output, possibly partial when
	// error is set. Capture is bounded; when a stream produces more than
	// the guest keeps, the oldest bytes are dropped and the stream's
	// truncated flag is set.
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	// exit_code is the command's exit code. Meaningless when error is set.
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// error is set when the command did not run to an exit code of its
	// own: it failed to start, timed out, or was killed by a signal.
	Error           string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	StdoutTruncated bool   `protobuf:"varint,5,opt,name=stdout_truncated,json=stdoutTruncated,proto3" json:"stdout_truncated,omitempty"`
	StderrTruncated bool   `protobuf:"varint,6,opt,name=stderr_truncated,json=stderrTruncated,proto3" json:"stderr_truncated,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{1}
}

func (x *ExecResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ExecResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecResponse) GetStdoutTruncated() bool {
	if x != nil {
		return x.StdoutTruncated
	}
	return false
}

func (x *ExecResponse) GetStderrTruncated() bool {
	if x != nil {
		return x.StderrTruncated
	}
	return false
}

// StartRequest describes a background process.
type StartRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// command is the shell command line to run. Required.
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// cwd is the working directory. Defaults to the guest's working
	// directory.
	Cwd string `protobuf:"bytes,2,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// env holds environment variables set on top of the guest's own.
	Env           map[string]string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{2}
}

func (x *StartRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *StartRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *StartRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type StartResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// process_id identifies the process for Get/WriteStdin/Signal.
	ProcessId     string `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{3}
}

func (x *StartResponse) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

// GetRequest polls a background process.
type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// process_id of the process to poll. Required.
	ProcessId string `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	// stdout_offset and stderr_offset are the absolute byte offsets to
	// read output from — normally the offsets a previous Get returned.
	StdoutOffset int64 `protobuf:"varint,2,opt,name=stdout_offset,json=stdoutOffset,proto3" json:"stdout_offset,omitempty"`
	StderrOffset int64 `protobuf:"varint,3,opt,name=stderr_offset,json=stderrOffset,proto3" json:"stderr_offset,omitempty"`
	// wait_ms long-polls: the call returns as soon as there is output at
	// or past the requested offsets or the process exits, and after
	// wait_ms at the latest. The server caps the wait below the atenet
	// router's route timeout, so a held poll is never mistaken for a dead
	// connection. 0 returns immediately.
	WaitMs        int64 `protobuf:"varint,4,opt,name=wait_ms,json=waitMs,proto3" json:"wait_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *GetRequest) GetStdoutOffset() int64 {
	if x != nil {
		return x.StdoutOffset
	}
	return 0
}

func (x *GetRequest) GetStderrOffset() int64 {
	if x != nil {
		return x.StderrOffset
	}
	return 0
}

func (x *GetRequest) GetWaitMs() int64 {
	if x != nil {
		return x.WaitMs
	}
	return 0
}

type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// process is the process's current state.
	Process *ProcessInfo `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	// stdout and stderr hold output starting at stdout_offset and
	// stderr_offset. The buffers are bounded, so the start offsets can be
	// later than requested when old output has been discarded; the next
	// poll continues from offset + len(bytes).
	Stdout        []byte `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	StdoutOffset  int64  `protobuf:"varint,3,opt,name=stdout_offset,json=stdoutOffset,proto3" json:"stdout_offset,omitempty"`
	Stderr        []byte `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	StderrOffset  int64  `protobuf:"varint,5,opt,name=stderr_offset,json=stderrOffset,proto3" json:"stderr_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{5}
}

func (x *GetResponse) GetProcess() *ProcessInfo {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *GetResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *GetResponse) GetStdoutOffset() int64 {
	if x != nil {
		return x.StdoutOffset
	}
	return 0
}

func (x *GetResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *GetResponse) GetStderrOffset() int64 {
	if x != nil {
		return x.StderrOffset
	}
	return 0
}

type WriteStdinRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// process_id of the process to write to. Required.
	ProcessId string `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	// data is appended to the process's standard input.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// close_stdin closes the process's standard input after writing data.
	CloseStdin    bool `protobuf:"varint,3,opt,name=close_stdin,json=closeStdin,proto3" json:"close_stdin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteStdinRequest) Reset() {
	*x = WriteStdinRequest{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteStdinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteStdinRequest) ProtoMessage() {}

func (x *WriteStdinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteStdinRequest.ProtoReflect.Descriptor instead.
func (*WriteStdinRequest) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{6}
}

func (x *WriteStdinRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *WriteStdinRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WriteStdinRequest) GetCloseStdin() bool {
	if x != nil {
		return x.CloseStdin
	}
	return false
}

type WriteStdinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteStdinResponse) Reset() {
	*x = WriteStdinResponse{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteStdinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteStdinResponse) ProtoMessage() {}

func (x *WriteStdinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteStdinResponse.ProtoReflect.Descriptor instead.
func (*WriteStdinResponse) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{7}
}

type SignalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// process_id of the process to signal. Required.
	ProcessId string `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	// signal is the POSIX signal number, e.g. 15 for SIGTERM and 9 for
	// SIGKILL. It is delivered to the whole process group.
	Signal        int32 `protobuf:"varint,2,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalRequest) Reset() {
	*x = SignalRequest{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRequest) ProtoMessage() {}

func (x *SignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRequest.ProtoReflect.Descriptor instead.
func (*SignalRequest) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{8}
}

func (x *SignalRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *SignalRequest) GetSignal() int32 {
	if x != nil {
		return x.Signal
	}
	return 0
}

type SignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{9}
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{10}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*ProcessInfo         `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{11}
}

func (x *ListResponse) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

// ProcessInfo is the durable record of a background process.
type ProcessInfo struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProcessId string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	// command is the shell command line the process runs.
	Command   string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	StartTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// exited is set once the process has exited; its presence is the
	// in-band signal that the operation is done.
	Exited *ExitStatus `protobuf:"bytes,4,opt,name=exited,proto3" json:"exited,omitempty"`
	// stdout_len and stderr_len are the total bytes each stream has
	// produced so far — the offsets at the end of the output.
	StdoutLen     int64 `protobuf:"varint,5,opt,name=stdout_len,json=stdoutLen,proto3" json:"stdout_len,omitempty"`
	StderrLen     int64 `protobuf:"varint,6,opt,name=stderr_len,json=stderrLen,proto3" json:"stderr_len,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{12}
}

func (x *ProcessInfo) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *ProcessInfo) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ProcessInfo) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ProcessInfo) GetExited() *ExitStatus {
	if x != nil {
		return x.Exited
	}
	return nil
}

func (x *ProcessInfo) GetStdoutLen() int64 {
	if x != nil {
		return x.StdoutLen
	}
	return 0
}

func (x *ProcessInfo) GetStderrLen() int64 {
	if x != nil {
		return x.StderrLen
	}
	return 0
}

// ExitStatus reports how a process ended.
type ExitStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// exit_code is the process's exit code. Meaningless when error is set.
	ExitCode int32 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// error is set when the process did not run to an exit code of its
	// own: it failed to start or was killed by a signal.
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ExitTime      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=exit_time,json=exitTime,proto3" json:"exit_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitStatus) Reset() {
	*x = ExitStatus{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitStatus) ProtoMessage() {}

func (x *ExitStatus) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitStatus.ProtoReflect.Descriptor instead.
func (*ExitStatus) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{13}
}

func (x *ExitStatus) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExitStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExitStatus) GetExitTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExitTime
	}
	return nil
}

type ReadFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// path of the file to read. Relative paths resolve against the guest's
	// working directory. Required.
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{14}
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data is the next chunk of the file.
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{15}
}

func (x *ReadFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// WriteFileRequest is one message of a WriteFile stream. path and mode
// are read from the first message; every message may carry data.
type WriteFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// path of the file to write. Parent directories are created as needed.
	// Required on the first message.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// mode is the POSIX file mode, e.g. 0644. Defaults to 0644.
	Mode uint32 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	// data is the next chunk of the file.
	Data          []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{16}
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *WriteFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bytes_written is the total number of bytes written.
	BytesWritten  int64 `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{17}
}

func (x *WriteFileResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

type StatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// path of the file or directory. Required.
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{18}
}

func (x *StatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *FileInfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{19}
}

func (x *StatResponse) GetInfo() *FileInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type ListDirRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// path of the directory to list. Required.
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirRequest) Reset() {
	*x = ListDirRequest{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirRequest) ProtoMessage() {}

func (x *ListDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirRequest.ProtoReflect.Descriptor instead.
func (*ListDirRequest) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{20}
}

func (x *ListDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*FileInfo            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirResponse) Reset() {
	*x = ListDirResponse{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirResponse) ProtoMessage() {}

func (x *ListDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirResponse.ProtoReflect.Descriptor instead.
func (*ListDirResponse) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{21}
}

func (x *ListDirResponse) GetEntries() []*FileInfo {
	if x != nil {
		return x.Entries
	}
	return nil
}

type MkdirRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// path of the directory to create. Required.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// parents creates missing parent directories instead of failing.
	Parents       bool `protobuf:"varint,2,opt,name=parents,proto3" json:"parents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{22}
}

func (x *MkdirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MkdirRequest) GetParents() bool {
	if x != nil {
		return x.Parents
	}
	return false
}

type MkdirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirResponse) Reset() {
	*x = MkdirResponse{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirResponse) ProtoMessage() {}

func (x *MkdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirResponse.ProtoReflect.Descriptor instead.
func (*MkdirResponse) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{23}
}

type RemoveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// path of the file or directory to delete. Required.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// recursive deletes directories and their contents; without it,
	// removing a non-empty directory fails.
	Recursive     bool `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{24}
}

func (x *RemoveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RemoveRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type RemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponse.ProtoReflect.Descriptor instead.
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{25}
}

// FileInfo is the metadata of one file or directory.
type FileInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the base name of the entry.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// size in bytes, for regular files.
	Size int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// mode is the POSIX file mode.
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	IsDir         bool                   `protobuf:"varint,4,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	ModTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ateenv_v1alpha1_guest_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_ateenv_v1alpha1_guest_proto_rawDescGZIP(), []int{26}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileInfo) GetModTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModTime
	}
	return nil
}

var File_ateenv_v1alpha1_guest_proto protoreflect.FileDescriptor

const file_ateenv_v1alpha1_guest_proto_rawDesc = "" +
	"\n" +
	"\x1bateenv/v1alpha1/guest.proto\x12\x0fateenv.v1alpha1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdf\x01\n" +
	"\vExecRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x10\n" +
	"\x03cwd\x18\x02 \x01(\tR\x03cwd\x127\n" +
	"\x03env\x18\x03 \x03(\v2%.ateenv.v1alpha1.ExecRequest.EnvEntryR\x03env\x12\x14\n" +
	"\x05stdin\x18\x04 \x01(\fR\x05stdin\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\x03R\ttimeoutMs\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc7\x01\n" +
	"\fExecResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\fR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12)\n" +
	"\x10stdout_truncated\x18\x05 \x01(\bR\x0fstdoutTruncated\x12)\n" +
	"\x10stderr_truncated\x18\x06 \x01(\bR\x0fstderrTruncated\"\xac\x01\n" +
	"\fStartRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x10\n" +
	"\x03cwd\x18\x02 \x01(\tR\x03cwd\x128\n" +
	"\x03env\x18\x03 \x03(\v2&.ateenv.v1alpha1.StartRequest.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\rStartResponse\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\"\x8e\x01\n" +
	"\n" +
	"GetRequest\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12#\n" +
	"\rstdout_offset\x18\x02 \x01(\x03R\fstdoutOffset\x12#\n" +
	"\rstderr_offset\x18\x03 \x01(\x03R\fstderrOffset\x12\x17\n" +
	"\await_ms\x18\x04 \x01(\x03R\x06waitMs\"\xbf\x01\n" +
	"\vGetResponse\x126\n" +
	"\aprocess\x18\x01 \x01(\v2\x1c.ateenv.v1alpha1.ProcessInfoR\aprocess\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\fR\x06stdout\x12#\n" +
	"\rstdout_offset\x18\x03 \x01(\x03R\fstdoutOffset\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\fR\x06stderr\x12#\n" +
	"\rstderr_offset\x18\x05 \x01(\x03R\fstderrOffset\"g\n" +
	"\x11WriteStdinRequest\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1f\n" +
	"\vclose_stdin\x18\x03 \x01(\bR\n" +
	"closeStdin\"\x14\n" +
	"\x12WriteStdinResponse\"F\n" +
	"\rSignalRequest\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\x05R\x06signal\"\x10\n" +
	"\x0eSignalResponse\"\r\n" +
	"\vListRequest\"J\n" +
	"\fListResponse\x12:\n" +
	"\tprocesses\x18\x01 \x03(\v2\x1c.ateenv.v1alpha1.ProcessInfoR\tprocesses\"\xf4\x01\n" +
	"\vProcessInfo\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x123\n" +
	"\x06exited\x18\x04 \x01(\v2\x1b.ateenv.v1alpha1.ExitStatusR\x06exited\x12\x1d\n" +
	"\n" +
	"stdout_len\x18\x05 \x01(\x03R\tstdoutLen\x12\x1d\n" +
	"\n" +
	"stderr_len\x18\x06 \x01(\x03R\tstderrLen\"x\n" +
	"\n" +
	"ExitStatus\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x127\n" +
	"\texit_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bexitTime\"%\n" +
	"\x0fReadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"&\n" +
	"\x10ReadFileResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"N\n" +
	"\x10WriteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"8\n" +
	"\x11WriteFileResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x03R\fbytesWritten\"!\n" +
	"\vStatRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"=\n" +
	"\fStatResponse\x12-\n" +
	"\x04info\x18\x01 \x01(\v2\x19.ateenv.v1alpha1.FileInfoR\x04info\"$\n" +
	"\x0eListDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"F\n" +
	"\x0fListDirResponse\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.ateenv.v1alpha1.FileInfoR\aentries\"<\n" +
	"\fMkdirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\aparents\x18\x02 \x01(\bR\aparents\"\x0f\n" +
	"\rMkdirResponse\"A\n" +
	"\rRemoveRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\"\x10\n" +
	"\x0eRemoveResponse\"\x94\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\x12\x15\n" +
	"\x06is_dir\x18\x04 \x01(\bR\x05isDir\x125\n" +
	"\bmod_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\amodTime2\xbf\x03\n" +
	"\aProcess\x12C\n" +
	"\x04Exec\x12\x1c.ateenv.v1alpha1.ExecRequest\x1a\x1d.ateenv.v1alpha1.ExecResponse\x12F\n" +
	"\x05Start\x12\x1d.ateenv.v1alpha1.StartRequest\x1a\x1e.ateenv.v1alpha1.StartResponse\x12@\n" +
	"\x03Get\x12\x1b.ateenv.v1alpha1.GetRequest\x1a\x1c.ateenv.v1alpha1.GetResponse\x12U\n" +
	"\n" +
	"WriteStdin\x12\".ateenv.v1alpha1.WriteStdinRequest\x1a#.ateenv.v1alpha1.WriteStdinResponse\x12I\n" +
	"\x06Signal\x12\x1e.ateenv.v1alpha1.SignalRequest\x1a\x1f.ateenv.v1alpha1.SignalResponse\x12C\n" +
	"\x04List\x12\x1c.ateenv.v1alpha1.ListRequest\x1a\x1d.ateenv.v1alpha1.ListResponse2\xdb\x03\n" +
	"\n" +
	"FileSystem\x12Q\n" +
	"\bReadFile\x12 .ateenv.v1alpha1.ReadFileRequest\x1a!.ateenv.v1alpha1.ReadFileResponse0\x01\x12T\n" +
	"\tWriteFile\x12!.ateenv.v1alpha1.WriteFileRequest\x1a\".ateenv.v1alpha1.WriteFileResponse(\x01\x12C\n" +
	"\x04Stat\x12\x1c.ateenv.v1alpha1.StatRequest\x1a\x1d.ateenv.v1alpha1.StatResponse\x12L\n" +
	"\aListDir\x12\x1f.ateenv.v1alpha1.ListDirRequest\x1a .ateenv.v1alpha1.ListDirResponse\x12F\n" +
	"\x05Mkdir\x12\x1d.ateenv.v1alpha1.MkdirRequest\x1a\x1e.ateenv.v1alpha1.MkdirResponse\x12I\n" +
	"\x06Remove\x12\x1e.ateenv.v1alpha1.RemoveRequest\x1a\x1f.ateenv.v1alpha1.RemoveResponseBEZCgithub.com/agent-substrate/env/proto/ateenv/v1alpha1;ateenvv1alpha1b\x06proto3"

var (
	file_ateenv_v1alpha1_guest_proto_rawDescOnce sync.Once
	file_ateenv_v1alpha1_guest_proto_rawDescData []byte
)

func file_ateenv_v1alpha1_guest_proto_rawDescGZIP() []byte {
	file_ateenv_v1alpha1_guest_proto_rawDescOnce.Do(func() {
		file_ateenv_v1alpha1_guest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ateenv_v1alpha1_guest_proto_rawDesc), len(file_ateenv_v1alpha1_guest_proto_rawDesc)))
	})
	return file_ateenv_v1alpha1_guest_proto_rawDescData
}

var file_ateenv_v1alpha1_guest_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_ateenv_v1alpha1_guest_proto_goTypes = []any{
	(*ExecRequest)(nil),           // 0: ateenv.v1alpha1.ExecRequest
	(*ExecResponse)(nil),          // 1: ateenv.v1alpha1.ExecResponse
	(*StartRequest)(nil),          // 2: ateenv.v1alpha1.StartRequest
	(*StartResponse)(nil),         // 3: ateenv.v1alpha1.StartResponse
	(*GetRequest)(nil),            // 4: ateenv.v1alpha1.GetRequest
	(*GetResponse)(nil),           // 5: ateenv.v1alpha1.GetResponse
	(*WriteStdinRequest)(nil),     // 6: ateenv.v1alpha1.WriteStdinRequest
	(*WriteStdinResponse)(nil),    // 7: ateenv.v1alpha1.WriteStdinResponse
	(*SignalRequest)(nil),         // 8: ateenv.v1alpha1.SignalRequest
	(*SignalResponse)(nil),        // 9: ateenv.v1alpha1.SignalResponse
	(*ListRequest)(nil),           // 10: ateenv.v1alpha1.ListRequest
	(*ListResponse)(nil),          // 11: ateenv.v1alpha1.ListResponse
	(*ProcessInfo)(nil),           // 12: ateenv.v1alpha1.ProcessInfo
	(*ExitStatus)(nil),            // 13: ateenv.v1alpha1.ExitStatus
	(*ReadFileRequest)(nil),       // 14: ateenv.v1alpha1.ReadFileRequest
	(*ReadFileResponse)(nil),      // 15: ateenv.v1alpha1.ReadFileResponse
	(*WriteFileRequest)(nil),      // 16: ateenv.v1alpha1.WriteFileRequest
	(*WriteFileResponse)(nil),     // 17: ateenv.v1alpha1.WriteFileResponse
	(*StatRequest)(nil),           // 18: ateenv.v1alpha1.StatRequest
	(*StatResponse)(nil),          // 19: ateenv.v1alpha1.StatResponse
	(*ListDirRequest)(nil),        // 20: ateenv.v1alpha1.ListDirRequest
	(*ListDirResponse)(nil),       // 21: ateenv.v1alpha1.ListDirResponse
	(*MkdirRequest)(nil),          // 22: ateenv.v1alpha1.MkdirRequest
	(*MkdirResponse)(nil),         // 23: ateenv.v1alpha1.MkdirResponse
	(*RemoveRequest)(nil),         // 24: ateenv.v1alpha1.RemoveRequest
	(*RemoveResponse)(nil),        // 25: ateenv.v1alpha1.RemoveResponse
	(*FileInfo)(nil),              // 26: ateenv.v1alpha1.FileInfo
	nil,                           // 27: ateenv.v1alpha1.ExecRequest.EnvEntry
	nil,                           // 28: ateenv.v1alpha1.StartRequest.EnvEntry
	(*timestamppb.Timestamp)(nil), // 29: google.protobuf.Timestamp
}
var file_ateenv_v1alpha1_guest_proto_depIdxs = []int32{
	27, // 0: ateenv.v1alpha1.ExecRequest.env:type_name -> ateenv.v1alpha1.ExecRequest.EnvEntry
	28, // 1: ateenv.v1alpha1.StartRequest.env:type_name -> ateenv.v1alpha1.StartRequest.EnvEntry
	12, // 2: ateenv.v1alpha1.GetResponse.process:type_name -> ateenv.v1alpha1.ProcessInfo
	12, // 3: ateenv.v1alpha1.ListResponse.processes:type_name -> ateenv.v1alpha1.ProcessInfo
	29, // 4: ateenv.v1alpha1.ProcessInfo.start_time:type_name -> google.protobuf.Timestamp
	13, // 5: ateenv.v1alpha1.ProcessInfo.exited:type_name -> ateenv.v1alpha1.ExitStatus
	29, // 6: ateenv.v1alpha1.ExitStatus.exit_time:type_name -> google.protobuf.Timestamp
	26, // 7: ateenv.v1alpha1.StatResponse.info:type_name -> ateenv.v1alpha1.FileInfo
	26, // 8: ateenv.v1alpha1.ListDirResponse.entries:type_name -> ateenv.v1alpha1.FileInfo
	29, // 9: ateenv.v1alpha1.FileInfo.mod_time:type_name -> google.protobuf.Timestamp
	0,  // 10: ateenv.v1alpha1.Process.Exec:input_type -> ateenv.v1alpha1.ExecRequest
	2,  // 11: ateenv.v1alpha1.Process.Start:input_type -> ateenv.v1alpha1.StartRequest
	4,  // 12: ateenv.v1alpha1.Process.Get:input_type -> ateenv.v1alpha1.GetRequest
	6,  // 13: ateenv.v1alpha1.Process.WriteStdin:input_type -> ateenv.v1alpha1.WriteStdinRequest
	8,  // 14: ateenv.v1alpha1.Process.Signal:input_type -> ateenv.v1alpha1.SignalRequest
	10, // 15: ateenv.v1alpha1.Process.List:input_type -> ateenv.v1alpha1.ListRequest
	14, // 16: ateenv.v1alpha1.FileSystem.ReadFile:input_type -> ateenv.v1alpha1.ReadFileRequest
	16, // 17: ateenv.v1alpha1.FileSystem.WriteFile:input_type -> ateenv.v1alpha1.WriteFileRequest
	18, // 18: ateenv.v1alpha1.FileSystem.Stat:input_type -> ateenv.v1alpha1.StatRequest
	20, // 19: ateenv.v1alpha1.FileSystem.ListDir:input_type -> ateenv.v1alpha1.ListDirRequest
	22, // 20: ateenv.v1alpha1.FileSystem.Mkdir:input_type -> ateenv.v1alpha1.MkdirRequest
	24, // 21: ateenv.v1alpha1.FileSystem.Remove:input_type -> ateenv.v1alpha1.RemoveRequest
	1,  // 22: ateenv.v1alpha1.Process.Exec:output_type -> ateenv.v1alpha1.ExecResponse
	3,  // 23: ateenv.v1alpha1.Process.Start:output_type -> ateenv.v1alpha1.StartResponse
	5,  // 24: ateenv.v1alpha1.Process.Get:output_type -> ateenv.v1alpha1.GetResponse
	7,  // 25: ateenv.v1alpha1.Process.WriteStdin:output_type -> ateenv.v1alpha1.WriteStdinResponse
	9,  // 26: ateenv.v1alpha1.Process.Signal:output_type -> ateenv.v1alpha1.SignalResponse
	11, // 27: ateenv.v1alpha1.Process.List:output_type -> ateenv.v1alpha1.ListResponse
	15, // 28: ateenv.v1alpha1.FileSystem.ReadFile:output_type -> ateenv.v1alpha1.ReadFileResponse
	17, // 29: ateenv.v1alpha1.FileSystem.WriteFile:output_type -> ateenv.v1alpha1.WriteFileResponse
	19, // 30: ateenv.v1alpha1.FileSystem.Stat:output_type -> ateenv.v1alpha1.StatResponse
	21, // 31: ateenv.v1alpha1.FileSystem.ListDir:output_type -> ateenv.v1alpha1.ListDirResponse
	23, // 32: ateenv.v1alpha1.FileSystem.Mkdir:output_type -> ateenv.v1alpha1.MkdirResponse
	25, // 33: ateenv.v1alpha1.FileSystem.Remove:output_type -> ateenv.v1alpha1.RemoveResponse
	22, // [22:34] is the sub-list for method output_type
	10, // [10:22] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_ateenv_v1alpha1_guest_proto_init() }
func file_ateenv_v1alpha1_guest_proto_init() {
	if File_ateenv_v1alpha1_guest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ateenv_v1alpha1_guest_proto_rawDesc), len(file_ateenv_v1alpha1_guest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_ateenv_v1alpha1_guest_proto_goTypes,
		DependencyIndexes: file_ateenv_v1alpha1_guest_proto_depIdxs,
		MessageInfos:      file_ateenv_v1alpha1_guest_proto_msgTypes,
	}.Build()
	File_ateenv_v1alpha1_guest_proto = out.File
	file_ateenv_v1alpha1_guest_proto_goTypes = nil
	file_ateenv_v1alpha1_guest_proto_depIdxs = nil
}
